const FTP = require('ftp');
const mysql = require('mysql2/promise');
const path = require('path');
try {
    var config = require("../../config/Zconfig.json");
} catch(e) {
    var config = {};
}
var dcolJSONcontroller = require('./dcolJSONController');
const stream = require('stream');
const monitoringIntervals = {};
const runningProcesses = {};

const tableHeaders = {
    dcollect_a: ['TIMESTAMP','DCUOUTH','DCURDW','DCULENG','DCUVERS1','DCUVERS2','DCUVERSC','DCUBCVER','DCUSGVER','DCURCTYP','DCUVERS','DCUSYSID','DCUTMSTP','DCUTIME','DCUDATE','DCUOUTH_LEN','DCASSOC','DCADSNAM','DCAASSOC','DCAFLAG1','DCAFLAG2','DCAHURBA','DCAHARBA','DCANLR','DCADLR','DCAINR','DCAUPR','DCARTR','DCAASP','DCACIS','DCACAS','DCAEXC','DCARKP','DCAKLN','DCAHURBC','DCAHARBC','DCACISZ','DCACACI','DCATRDT','DCASSOCE'],
    dcollect_ai: ['TIMESTAMP','DCUOUTH','DCURDW','DCULENG','DCUVERS1','DCUVERS2','DCUVERSC','DCUBCVER','DCUSGVER','DCURCTYP','DCUVERS','DCUSYSID','DCUTMSTP','DCUTIME','DCUDATE','DCUOUTH_LEN','DAIDATA','DAIDRTN','DAIDDATE','DAIDDSNM','DAIDDSMR','DAIDSRID','DAIDTIME','DAIMRTN','DAIMDATE','DAIMDSNM','DAIMDSMR','DAIMSRID','DAIMTIME','DAISRTN','DAISDATE','DAISDSNM','DAISDSMR','DAISSRID','DAISTIME','DAIGRTN','DAIGDATE','DAIGDSNM','DAIGDSMR','DAIGSRID','DAIGTIME'],
    dcollect_b: ['TIMESTAMP','DCUOUTH','DCURDW','DCULENG','DCUVERS1','DCUVERS2','DCUVERSC','DCUBCVER','DCUSGVER','DCURCTYP','DCUVERS','DCUSYSID','DCUTMSTP','DCUTIME','DCUDATE','DCUOUTH_LEN','UB_RETAINDAYS','UB_USER_DATASIZE','UB_COMP_DATASIZE','UBALLSP','UBBKLNG','UBBDSIE','UBCLASS','UBDSNAM','UBDEVCL','UBDSORG','UBDSIZE','UBDATE','UBDCLNG','UBDATCL','UBENCRPT','UBFLAG1','UBFLAG2','UBFLAG3','UBFRVOL','UBFLAG4','UBMCLAS','UBMCLNG','UBMGTCL','UBPDSEV','UBRECSP','UBSCLNG','UBSTGCL','UBUSESP','UBUNIXFILE','UBUPATHL','UBUPATHN'],
    dcollect_bc: ['TIMESTAMP','DCUOUTH','DCURDW','DCULENG','DCUVERS1','DCUVERS2','DCUVERSC','DCUBCVER','DCUSGVER','DCURCTYP','DCUVERS','DCUSYSID','DCUTMSTP','DCUTIME','DCUDATE','DCUOUTH_LEN','DBCDATA','DBCUSER','DBCDATE','DBCTIME','DBCDESC','DBCFLAGS','DBCFLGDC','DBCDEFMC','DBCMCLEN','DBCMCNAM','DBCTRKSZ','DBCCYLCP','DBCDUNIT','DBCSRST','DBCSTAT','DBCFSYSN_1','DBCFSYSN_2','DBCFSYSN_3','DBCFSYSN_4','DBCFSYSN_5','DBCFSYSN_6','DBCFSYSN_7','DBCFSYSN_8','DBCSCDSN','DBCSFEAT_1','DBCSFEAT_2','DBCSFEAT_3','DBCSFEAT_4','DBCSFEAT_5','DBCSFEAT_6','DBCSFEAT_7','DBCSFEAT_8','DBCSYSNT_1','DBCSYSNT_2','DBCSYSNT_3','DBCSYSNT_4','DBCSYSNT_5','DBCSYSNT_6','DBCSYSNT_7','DBCSYSNT_8','DBCSYSNM_1','DBCSYSNM_2','DBCSYSNM_3','DBCSYSNM_4','DBCSYSNM_5','DBCSYSNM_6','DBCSYSNM_7','DBCSYSNM_8','DBCSYSNM_9','DBCSYSNM_10','DBCSYSNM_11','DBCSYSNM_12','DBCSYSNM_13','DBCSYSNM_14','DBCSYSNM_15','DBCSYSNM_16','DBCSYSNM_17','DBCSYSNM_18','DBCSYSNM_19','DBCSYSNM_20','DBCSYSNM_21','DBCSYSNM_22','DBCSYSNM_23','DBCSYSNM_24','DBCSYSNM_25','DBCSYSNM_26','DBCSYSNM_27','DBCSYSNM_28','DBCSYSNM_29','DBCSYSNM_30','DBCSYSNM_31','DBCSYSNM_32','DBCSYSFT_1','DBCSYSFT_2','DBCSYSFT_3','DBCSYSFT_4','DBCSYSFT_5','DBCSYSFT_6','DBCSYSFT_7','DBCSYSFT_8','DBCSYSFT_9','DBCSYSFT_10','DBCSYSFT_11','DBCSYSFT_12','DBCSYSFT_13','DBCSYSFT_14','DBCSYSFT_15','DBCSYSFT_16','DBCSYSFT_17','DBCSYSFT_18','DBCSYSFT_19','DBCSYSFT_20','DBCSYSFT_21','DBCSYSFT_22','DBCSYSFT_23','DBCSYSFT_24','DBCSYSFT_25','DBCSYSFT_26','DBCSYSFT_27','DBCSYSFT_28','DBCSYSFT_29','DBCSYSFT_30','DBCSYSFT_31','DBCSYSFT_32','DBCSNMTY_1','DBCSNMTY_2','DBCSNMTY_3','DBCSNMTY_4','DBCSNMTY_5','DBCSNMTY_6','DBCSNMTY_7','DBCSNMTY_8','DBCSNMTY_9','DBCSNMTY_10','DBCSNMTY_11','DBCSNMTY_12','DBCSNMTY_13','DBCSNMTY_14','DBCSNMTY_15','DBCSNMTY_16','DBCSNMTY_17','DBCSNMTY_18','DBCSNMTY_19','DBCSNMTY_20','DBCSNMTY_21','DBCSNMTY_22','DBCSNMTY_23','DBCSNMTY_24','DBCSNMTY_25','DBCSNMTY_26','DBCSNMTY_27','DBCSNMTY_28','DBCSNMTY_29','DBCSNMTY_30','DBCSNMTY_31','DBCSNMTY_32','DBCSEPNL','DBCSEPNM'],
    dcollect_c: ['TIMESTAMP','DCUOUTH','DCURDW','DCULENG','DCUVERS1','DCUVERS2','DCUVERSC','DCUBCVER','DCUSGVER','DCURCTYP','DCUVERS','DCUSYSID','DCUTMSTP','DCUTIME','DCUDATE','DCUOUTH_LEN','UCAFOCC','UCBFOCC','UCCOLDT','UCCAPDE','UCFLAG1','UCINTVM','UCNOMIG','UCNINTV','UCTOTAL','UCTGOCC','UCTROCC','UCVOLSR'],
    dcollect_d: ['TIMESTAMP','DCUOUTH','DCURDW','DCULENG','DCUVERS1','DCUVERS2','DCUVERSC','DCUBCVER','DCUSGVER','DCURCTYP','DCUVERS','DCUSYSID','DCUTMSTP','DCUTIME','DCUDATE','DCUOUTH_LEN','DCDADSI','DCDDSNAM','DCDERROR','DCDFLAG1','DCDFLAG2','DCDFLAG3','DCDDSOR0_1','DCDDSOR1_1','DCDRECRD','DCDNMEXT','DCDVOLSR','DCDBKLNG','DCDLRECL','DCDALLSP','DCDUSESP','DCDSCALL','DCDNMBLK','DCDCREDT','DCDEXPDT','DCDLSTRF','DCDDSSER','DCDVOLSQ','DCDLBKDT','DCDDCLAS','DCDDCLNG','DCDDATCL','DCDSCLAS','DCDSCLNG','DCDSTGCL','DCDMCLAS','DCDMCLNG','DCDMGTCL','DCDSTOGP','DCDSGLNG','DCDSTGRP','DCDCCSID','DCDCATF','DCDDSCBF','DCDUDSIZ','DCDCUDSZ','DCDEXFLG','DCDSCNT','DCDOVERA','DCDACCT','DCDFLAG5','DCDDS9F1','DCDJBNMC','DCDSTNMC','DCDTIMEC','DCDALLSX','DCDUSESX','DCDSCALX','DCDNMBLX','DCDXPSEV','DCDCTYPE','DCDAENCR','DCDATYPE','DCDAKLBL','DCDADSIE'],
    dcollect_dc: ['TIMESTAMP','DCUOUTH','DCURDW','DCULENG','DCUVERS1','DCUVERS2','DCUVERSC','DCUBCVER','DCUSGVER','DCURCTYP','DCUVERS','DCUSYSID','DCUTMSTP','DCUTIME','DCUDATE','DCUOUTH_LEN','DDCDATA','DDCNMFLD','DDCNMLEN','DDCNAME','DDCUSER','DDCDATE','DDCTIME','DDCDESC','DDCSPEC1_1','DDCSPEC2_1','DDCSPEC3_1','DDCSPEC4_1','DDCRCORG','DDCRECFM','DDCDSFLG','DDCCNTL','DDCRETPD','DDCEXPYR','DDCEXPDY','DDCVOLCT','DDCDSNTY','DDCSPPRI','DDCSPSEC','DDCDIBLK','DDCAVREC','DDCREDUC','DDCRBIAS','DDCDVC','DDCAUNIT','DDCLRECL','DDCCISZ','DDCFRSP','DDCCIPCT','DDCCAPCT','DDCSHROP','DDCXREG','DDCXSYS','DDCVINDX','DDCKLEN','DDCKOFF','DDCCAMT','DDCCOMP','DDCMEDIA','DDCRECTE','DDCRLS1','DDCBWOTP','DDCLOGRC','DDCSPAND','DDCFRLOG','DDCLOGNM','DDCLOGLN','DDCLOGID','DDCSPECA','DDCSPECB','DDCSPECC','DDCSPECD','DDCSFLG','DDCVSAM1','DDCVBYT1','DDCEATTR','DDCCT','DDCDSCF','DDCRBYTE','DDCBLKLM','DDCBSZLM','DDCTAPE1','DDCPSCA','DDCPSEG','DDCVSP','DDCVSPU','DDCVSPV','DDCKYLB1','DDCKLBL1','DDCKLBN1','DDCKYCD1','DDCKYLB2','DDCKLBL2','DDCKLBN2','DDCKYCD2','DDCRMODE','DDCDKYLB','DDCDKLBL','DDCDKLBN','DDCDATAE'],
    dcollect_lb: ['TIMESTAMP','DCUOUTH','DCURDW','DCULENG','DCUVERS1','DCUVERS2','DCUVERSC','DCUBCVER','DCUSGVER','DCURCTYP','DCUVERS','DCUSYSID','DCUTMSTP','DCUTIME','DCUDATE','DCUOUTH_LEN','DLBDATA','DLBNMFLD','DLBNMLEN','DLBLNAME','DLBNAME','DLBDUSER','DLBDDATE','DLBFLAGS','DLBDTIME','DLBOMST_1','DLBOMST_2','DLBOMST_3','DLBOMST_4','DLBOMST_5','DLBOMST_6','DLBOMST_7','DLBOMST_8','DLBSOUT_1','DLBSOUT_2','DLBSOUT_3','DLBSOUT_4','DLBSOUT_5','DLBSOUT_6','DLBSOUT_7','DLBSOUT_8','DLBCFCS_1','DLBCFCS_2','DLBCFCS_3','DLBCFCS_4','DLBCFCS_5','DLBCFCS_6','DLBCFCS_7','DLBCFCS_8','DLBTYPE','DLBDTYPE','DLBDCONS','DLBEDVT','DLBEJD','DLBLCBID','DLBEDUNM','DLBDEFDC','DLBDCLEN','DLBDCLNM','DLBDCNAM','DLBREQST_1','DLBREQST_2','DLBREQST_3','DLBREQST_4','DLBREQST_5','DLBREQST_6','DLBREQST_7','DLBREQST_8','DLBREQST_9','DLBREQST_10','DLBREQST_11','DLBREQST_12','DLBREQST_13','DLBREQST_14','DLBREQST_15','DLBREQST_16','DLBREQST_17','DLBREQST_18','DLBREQST_19','DLBREQST_20','DLBREQST_21','DLBREQST_22','DLBREQST_23','DLBREQST_24','DLBREQST_25','DLBREQST_26','DLBREQST_27','DLBREQST_28','DLBREQST_29','DLBREQST_30','DLBREQST_31','DLBREQST_32','DLBCURST_1','DLBCURST_2','DLBCURST_3','DLBCURST_4','DLBCURST_5','DLBCURST_6','DLBCURST_7','DLBCURST_8','DLBCURST_9','DLBCURST_10','DLBCURST_11','DLBCURST_12','DLBCURST_13','DLBCURST_14','DLBCURST_15','DLBCURST_16','DLBCURST_17','DLBCURST_18','DLBCURST_19','DLBCURST_20','DLBCURST_21','DLBCURST_22','DLBCURST_23','DLBCURST_24','DLBCURST_25','DLBCURST_26','DLBCURST_27','DLBCURST_28','DLBCURST_29','DLBCURST_30','DLBCURST_31','DLBCURST_32'],
    dcollect_m: ['TIMESTAMP','DCUOUTH','DCURDW','DCULENG','DCUVERS1','DCUVERS2','DCUVERSC','DCUBCVER','DCUSGVER','DCURCTYP','DCUVERS','DCUSYSID','DCUTMSTP','DCUTIME','DCUDATE','DCUOUTH_LEN','UM_USER_DATASIZE','UM_COMP_DATASIZE','UM_CLD_INFO','UM_CLOUD_NAME_LENGTH','UM_CLOUD_NAME','UM_CONTAINER_NAME','UM_OBJ_NUMBER','UM_CLD_COMP_PERCENT','UMALLSP','UMBKLNG','UMCREDT','UMDSNAM','UMDEVCL','UMDSORG','UMDSIZE','UMDATE','UMDCLAS','UMDCLNG','UMDATCL','UMEXPDT','UMENCRPT','UMENCRPL','UMFLAG1','UMFLAG2','UMFRVOL','UMFLAG3','UMFLAG4','UMLRFDT','UMMCLAS','UMMCLNG','UMMGTCL','UMMDSIE','UMNMIG','UMPDSEV','UMRECOR','UMRECSP','UMSCLNG','UMSTGCL','UMUSESP'],
    dcollect_mc: ['TIMESTAMP','DCUOUTH','DCURDW','DCULENG','DCUVERS1','DCUVERS2','DCUVERSC','DCUBCVER','DCUSGVER','DCURCTYP','DCUVERS','DCUSYSID','DCUTMSTP','DCUTIME','DCUDATE','DCUOUTH_LEN','DMCDATA','DMCNMLEN','DMCNAME','DMCUSER','DMCDATE','DMCTIME','DMCDESC','DMCSPEC1','DMCSPEC2','DMCRLF','DMCGDGFL','DMCPELEM','DMCEXPF','DMCEXPAC','DMCRDARC','DMCRETF','DMCRFMT','DMCEXPDY','DMCEXDAT','DMCEYEAR','DMCEDAY','DMCMIGF','DMCPRDY','DMCL1DY','DMCCMAU','DMCBKFLG','DMCBKFQ','DMCBKVS','DMCBVRD','DMCBKDY','DMCBKNP','DMCBADU','DMCCPYTC','DMCBKUDC','DMCMRETF','DMCMRTDY','DMCTSCR','DMCTSLU','DMCPERD','DMCVSCR','DMCVSCY','DMCVSCM','DMCVSCD','DMCVSLU','DMCVSUY','DMCVSUM','DMCVSUD','DMCVPRD','DMCVPMD','DMCVPQT','DMCVPQD','DMCVPQM','DMCVPYR','DMCVPYD','DMCVPYM','DMCCTSRL','DMCCTCPY','DMCCL2DY','DMCCLOUD','DMCCLLEN','DMCCLNAM','DMCSZLTE','DMCSZGT','DMCACLTE','DMCACGT','DMCDATAE'],
    dcollect_sc: ['TIMESTAMP','DCUOUTH','DCURDW','DCULENG','DCUVERS1','DCUVERS2','DCUVERSC','DCUBCVER','DCUSGVER','DCURCTYP','DCUVERS','DCUSYSID','DCUTMSTP','DCUTIME','DCUDATE','DCUOUTH_LEN','DSCDATA','DSCNMFLD','DSCNMLEN','DSCNAME','DSCUSER','DSCDATE','DSCTIME','DSCDESC','DSCFLAGS','DSCFLAG2','DSCVERSN','DSCBAKUP','DSCAVAIL','DSCDIRB','DSCSEQB','DSCACCES','DSCIACDL','DSCDIRR','DSCSEQR','DSCSTSDR','DSCCCHST','DSCCSLEN','DSCCSNAM','DSCDIRCW','DSCSEQCW','DSCPAV','DSCSTOSL','DSCVFLG2','DSCCMMFT','DSCDATAE'],
    dcollect_sg: ['TIMESTAMP','DCUOUTH','DCURDW','DCULENG','DCUVERS1','DCUVERS2','DCUVERSC','DCUBCVER','DCUSGVER','DCURCTYP','DCUVERS','DCUSYSID','DCUTMSTP','DCUTIME','DCUDATE','DCUOUTH_LEN','DSGDATA','DSGNMFLD','DSGNMLEN','DSGNAME','DSGUSER','DSGDATE','DSGTIME','DSGDESC','DSGFLAGS','DSGFLGDC','DSGFTYPE','DSGFHTHR','DSGFLTHR','DSGFVMAX','DSGFVUNT','DSGDMPCL_1','DSGDMPCL_2','DSGDMPCL_3','DSGDMPCL_4','DSGDMPCL_5','DSGSTAT_1','DSGSTAT_2','DSGSTAT_3','DSGSTAT_4','DSGSTAT_5','DSGSTAT_6','DSGSTAT_7','DSGSTAT_8','DSGABSYS','DSGADSYS','DSGAMSYS','DSGCSMSS_1','DSGCSMSS_2','DSGCSMSS_3','DSGCSMSS_4','DSGCSMSS_5','DSGCSMSS_6','DSGCSMSS_7','DSGCSMSS_8','DSGGBKUF','DSGTBLGR','DSGOAMFL','DSGCYLST','DSGCYLED','DSGVOLFT','DSGDRVST','DSGOLBNL_1','DSGOLBNL_2','DSGOLBNL_3','DSGOLBNL_4','DSGOLBNL_5','DSGOLBNL_6','DSGOLBNL_7','DSGOLBNL_8','DSGOLBNM_1','DSGOLBNM_2','DSGOLBNM_3','DSGOLBNM_4','DSGOLBNM_5','DSGOLBNM_6','DSGOLBNM_7','DSGOLBNM_8','DSGSYSST','DSGCNSMS','DSGOFLOW','DSGEXNLN','DSGEXNM','DSGFLAG2','DSGSBKPT','DSGSHTHR','DSGSLTHR','DSGRERV','DSGTOTAP','DSGTMSAP','DSGOAMID','DSGDATAE'],
    dcollect_t: ['TIMESTAMP','DCUOUTH','DCURDW','DCULENG','DCUVERS1','DCUVERS2','DCUVERSC','DCUBCVER','DCUSGVER','DCURCTYP','DCUVERS','DCUSYSID','DCUTMSTP','DCUTIME','DCUDATE','DCUOUTH_LEN','UTCAPTE','UTEMPTY','UTFULL','UTILP','UTPART','UTSTYPE'],
    dcollect_v: ['TIMESTAMP','DCUOUTH','DCURDW','DCULENG','DCUVERS1','DCUVERS2','DCUVERSC','DCUBCVER','DCUSGVER','DCURCTYP','DCUVERS','DCUSYSID','DCUTMSTP','DCUTIME','DCUDATE','DCUOUTH_LEN','DCVVOLI','DCVVOLSR','DCVFLAG1','DCVERROR','DCVPERCT','DCVFRESP','DCVALLOC','DCVVLCAP','DCVFRAGI','DCVLGEXT','DCVFREXT','DCVFDSCB','DCVFVIRS','DCVDVTYP','DCVDVNUM','DCVSTGGP','DCVSGLNG','DCVSGTCL','DCVDPTYP','DCVTRPCT','DCVEAVOL_1','DCVEAVOL_2','DCVEAVOL_3','DCVTRFSP','DCVTRALC','DCVTRVLC','DCVTRFRG','DCVTRLGE','DCVTRFRX','DCVFCYLS','DCVFTRKS','DCVVOLIE'],
    dcollect_vl: ['TIMESTAMP','DCUOUTH','DCURDW','DCULENG','DCUVERS1','DCUVERS2','DCUVERSC','DCUBCVER','DCUSGVER','DCURCTYP','DCUVERS','DCUSYSID','DCUTMSTP','DCUTIME','DCUDATE','DCUOUTH_LEN','DVLDATA','DVLNMLEN','DVLVSER','DVLUSER','DVLDATE','DVLTIME','DVLFLGDC','DVLSGLEN','DVLSTGRP','DVLSMSS_1','DVLSMSS_2','DVLSMSS_3','DVLSMSS_4','DVLSMSS_5','DVLSMSS_6','DVLSMSS_7','DVLSMSS_8','DVLMVSS_1','DVLMVSS_2','DVLMVSS_3','DVLMVSS_4','DVLMVSS_5','DVLMVSS_6','DVLMVSS_7','DVLMVSS_8','DVLCSMSS_1','DVLCSMSS_2','DVLCSMSS_3','DVLCSMSS_4','DVLCSMSS_5','DVLCSMSS_6','DVLCSMSS_7','DVLCSMSS_8','DVLNUCBA','DVLNTCPY','DVLNFREE','DVLNLEXT','DVLN0CNT','DVLTRKSZ','DVLNLEVL','DVLSTSMS_1','DVLSTSMS_2','DVLSTSMS_3','DVLSTSMS_4','DVLSTSMS_5','DVLSTSMS_6','DVLSTSMS_7','DVLSTSMS_8','DVLSTSMS_9','DVLSTSMS_10','DVLSTSMS_11','DVLSTSMS_12','DVLSTSMS_13','DVLSTSMS_14','DVLSTSMS_15','DVLSTSMS_16','DVLSTSMS_17','DVLSTSMS_18','DVLSTSMS_19','DVLSTSMS_20','DVLSTSMS_21','DVLSTSMS_22','DVLSTSMS_23','DVLSTSMS_24','DVLSTSMS_25','DVLSTSMS_26','DVLSTSMS_27','DVLSTSMS_28','DVLSTSMS_29','DVLSTSMS_30','DVLSTSMS_31','DVLSTSMS_32','DVLSTMVS_1','DVLSTMVS_2','DVLSTMVS_3','DVLSTMVS_4','DVLSTMVS_5','DVLSTMVS_6','DVLSTMVS_7','DVLSTMVS_8','DVLSTMVS_9','DVLSTMVS_10','DVLSTMVS_11','DVLSTMVS_12','DVLSTMVS_13','DVLSTMVS_14','DVLSTMVS_15','DVLSTMVS_16','DVLSTMVS_17','DVLSTMVS_18','DVLSTMVS_19','DVLSTMVS_20','DVLSTMVS_21','DVLSTMVS_22','DVLSTMVS_23','DVLSTMVS_24','DVLSTMVS_25','DVLSTMVS_26','DVLSTMVS_27','DVLSTMVS_28','DVLSTMVS_29','DVLSTMVS_30','DVLSTMVS_31','DVLSTMVS_32','DVLCNSMS_1','DVLCNSMS_2','DVLCNSMS_3','DVLCNSMS_4','DVLCNSMS_5','DVLCNSMS_6','DVLCNSMS_7','DVLCNSMS_8','DVLCNSMS_9','DVLCNSMS_10','DVLCNSMS_11','DVLCNSMS_12','DVLCNSMS_13','DVLCNSMS_14','DVLCNSMS_15','DVLCNSMS_16','DVLCNSMS_17','DVLCNSMS_18','DVLCNSMS_19','DVLCNSMS_20','DVLCNSMS_21','DVLCNSMS_22','DVLCNSMS_23','DVLCNSMS_24','DVLCNSMS_25','DVLCNSMS_26','DVLCNSMS_27','DVLCNSMS_28','DVLCNSMS_29','DVLCNSMS_30','DVLCNSMS_31','DVLCNSMS_32','DVLTRKCP','DVLTRKFR','DVLTRKEX','DVLDATAE']
};

function parseDirName(dirName) {
    const parts = dirName.split('_');
    if (parts.length >= 3 && parts[0].startsWith('D') && parts[0].length === 7 && parts[1].startsWith('T') && parts[1].length === 7) {
        const dateStr = parts[0].slice(1);
        const timeStr = parts[1].slice(1);
        const year = '20' + dateStr.slice(0, 2);
        const month = dateStr.slice(2, 4);
        const day = dateStr.slice(4, 6);
        const hour = timeStr.slice(0, 2);
        const minute = timeStr.slice(2, 4);
        const second = timeStr.slice(4, 6);
        return new Date(`${year}-${month}-${day}T${hour}:${minute}:${second}`);
    }
    return null;
}

function getTableNameFromFileName(fileName) {
    const metric = fileName.split('_')[1].split('.')[0].toLowerCase();
    return `dcollect_${metric}`;
}

async function createTables(connection) {
    console.log('Creating/checking tables...');
    
    // First check if tables exist
    const [tables] = await connection.query('SHOW TABLES');
    const existingTables = tables.map(t => Object.values(t)[0]);
    console.log('Existing tables:', existingTables);

    const createTableQueries = [
        `CREATE TABLE IF NOT EXISTS dcollect_a (
            id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
            TIMESTAMP DATETIME DEFAULT NULL,
            DCUOUTH INT DEFAULT NULL,
            DCURDW BIGINT DEFAULT NULL,
            DCULENG INT DEFAULT NULL,
            DCUVERS1 INT DEFAULT NULL,
            DCUVERS2 INT DEFAULT NULL,
            DCUVERSC INT DEFAULT NULL,
            DCUBCVER INT DEFAULT NULL,
            DCUSGVER INT DEFAULT NULL,
            DCURCTYP CHAR(2) DEFAULT NULL,
            DCUVERS INT DEFAULT NULL,
            DCUSYSID VARCHAR(8) DEFAULT NULL,
            DCUTMSTP VARCHAR(16) DEFAULT NULL,
            DCUTIME TIME DEFAULT NULL,
            DCUDATE VARCHAR(8) DEFAULT NULL,
            DCUOUTH_LEN INT DEFAULT NULL,
            DCASSOC VARCHAR(255) DEFAULT NULL,
            DCADSNAM VARCHAR(255) DEFAULT NULL,
            DCAASSOC VARCHAR(255) DEFAULT NULL,
            DCAFLAG1 INT DEFAULT NULL,
            DCAFLAG2 INT DEFAULT NULL,
            DCAHURBA BIGINT DEFAULT NULL,
            DCAHARBA BIGINT DEFAULT NULL,
            DCANLR INT DEFAULT NULL,
            DCADLR INT DEFAULT NULL,
            DCAINR INT DEFAULT NULL,
            DCAUPR INT DEFAULT NULL,
            DCARTR INT DEFAULT NULL,
            DCAASP INT DEFAULT NULL,
            DCACIS INT DEFAULT NULL,
            DCACAS INT DEFAULT NULL,
            DCAEXC INT DEFAULT NULL,
            DCARKP INT DEFAULT NULL,
            DCAKLN INT DEFAULT NULL,
            DCAHURBC BIGINT DEFAULT NULL,
            DCAHARBC BIGINT DEFAULT NULL,
            DCACISZ INT DEFAULT NULL,
            DCACACI INT DEFAULT NULL,
            DCATRDT INT DEFAULT NULL,
            DCASSOCE INT DEFAULT NULL
        )`,
        `CREATE TABLE IF NOT EXISTS dcollect_ai (
            id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
            TIMESTAMP DATETIME DEFAULT NULL,
            DCUOUTH INT DEFAULT NULL,
            DCURDW BIGINT DEFAULT NULL,
            DCULENG INT DEFAULT NULL,
            DCUVERS1 INT DEFAULT NULL,
            DCUVERS2 INT DEFAULT NULL,
            DCUVERSC INT DEFAULT NULL,
            DCUBCVER INT DEFAULT NULL,
            DCUSGVER INT DEFAULT NULL,
            DCURCTYP CHAR(2) DEFAULT NULL,
            DCUVERS INT DEFAULT NULL,
            DCUSYSID VARCHAR(8) DEFAULT NULL,
            DCUTMSTP VARCHAR(16) DEFAULT NULL,
            DCUTIME TIME DEFAULT NULL,
            DCUDATE VARCHAR(8) DEFAULT NULL,
            DCUOUTH_LEN INT DEFAULT NULL,
            DAIDATA INT DEFAULT NULL,
            DAIDRTN TEXT DEFAULT NULL,
            DAIDDATE VARCHAR(10) DEFAULT NULL,
            DAIDDSNM VARCHAR(255) DEFAULT NULL,
            DAIDDSMR VARCHAR(8) DEFAULT NULL,
            DAIDSRID VARCHAR(8) DEFAULT NULL,
            DAIDTIME TIME DEFAULT NULL,
            DAIMRTN TEXT DEFAULT NULL,
            DAIMDATE VARCHAR(10) DEFAULT NULL,
            DAIMDSNM VARCHAR(255) DEFAULT NULL,
            DAIMDSMR VARCHAR(8) DEFAULT NULL,
            DAIMSRID VARCHAR(8) DEFAULT NULL,
            DAIMTIME TIME DEFAULT NULL,
            DAISRTN TEXT DEFAULT NULL,
            DAISDATE VARCHAR(10) DEFAULT NULL,
            DAISDSNM VARCHAR(255) DEFAULT NULL,
            DAISDSMR VARCHAR(8) DEFAULT NULL,
            DAISSRID VARCHAR(8) DEFAULT NULL,
            DAISTIME TIME DEFAULT NULL,
            DAIGRTN TEXT DEFAULT NULL,
            DAIGDATE VARCHAR(10) DEFAULT NULL,
            DAIGDSNM VARCHAR(255) DEFAULT NULL,
            DAIGDSMR VARCHAR(8) DEFAULT NULL,
            DAIGSRID VARCHAR(8) DEFAULT NULL,
            DAIGTIME TIME DEFAULT NULL
        )`,
        `CREATE TABLE IF NOT EXISTS dcollect_b (
            id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
            TIMESTAMP DATETIME DEFAULT NULL,
            DCUOUTH INT DEFAULT NULL,
            DCURDW BIGINT DEFAULT NULL,
            DCULENG INT DEFAULT NULL,
            DCUVERS1 INT DEFAULT NULL,
            DCUVERS2 INT DEFAULT NULL,
            DCUVERSC INT DEFAULT NULL,
            DCUBCVER INT DEFAULT NULL,
            DCUSGVER INT DEFAULT NULL,
            DCURCTYP CHAR(2) DEFAULT NULL,
            DCUVERS INT DEFAULT NULL,
            DCUSYSID VARCHAR(8) DEFAULT NULL,
            DCUTMSTP VARCHAR(16) DEFAULT NULL,
            DCUTIME TIME DEFAULT NULL,
            DCUDATE VARCHAR(8) DEFAULT NULL,
            DCUOUTH_LEN INT DEFAULT NULL,
            UB_RETAINDAYS INT DEFAULT NULL,
            UB_USER_DATASIZE BIGINT DEFAULT NULL,
            UB_COMP_DATASIZE BIGINT DEFAULT NULL,
            UBALLSP INT DEFAULT NULL,
            UBBKLNG INT DEFAULT NULL,
            UBBDSIE INT DEFAULT NULL,
            UBCLASS VARCHAR(100) DEFAULT NULL,
            UBDSNAM VARCHAR(255) DEFAULT NULL,
            UBDEVCL CHAR(1) DEFAULT NULL,
            UBDSORG INT DEFAULT NULL,
            UBDSIZE INT DEFAULT NULL,
            UBDATE VARCHAR(8) DEFAULT NULL,
            UBDCLNG INT DEFAULT NULL,
            UBDATCL VARCHAR(100) DEFAULT NULL,
            UBENCRPT INT DEFAULT NULL,
            UBFLAG1 INT DEFAULT NULL,
            UBFLAG2 INT DEFAULT NULL,
            UBFLAG3 INT DEFAULT NULL,
            UBFRVOL VARCHAR(8) DEFAULT NULL,
            UBFLAG4 INT DEFAULT NULL,
            UBMCLAS VARCHAR(100) DEFAULT NULL,
            UBMCLNG INT DEFAULT NULL,
            UBMGTCL VARCHAR(100) DEFAULT NULL,
            UBPDSEV INT DEFAULT NULL,
            UBRECSP INT DEFAULT NULL,
            UBSCLNG INT DEFAULT NULL,
            UBSTGCL VARCHAR(100) DEFAULT NULL,
            UBUSESP INT DEFAULT NULL,
            UBUNIXFILE INT DEFAULT NULL,
            UBUPATHL INT DEFAULT NULL,
            UBUPATHN VARCHAR(255) DEFAULT NULL
        )`,
        `CREATE TABLE IF NOT EXISTS dcollect_bc (
            id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
            TIMESTAMP DATETIME DEFAULT NULL,
            DCUOUTH INT DEFAULT NULL,
            DCURDW BIGINT DEFAULT NULL,
            DCULENG INT DEFAULT NULL,
            DCUVERS1 INT DEFAULT NULL,
            DCUVERS2 INT DEFAULT NULL,
            DCUVERSC INT DEFAULT NULL,
            DCUBCVER INT DEFAULT NULL,
            DCUSGVER INT DEFAULT NULL,
            DCURCTYP CHAR(2) DEFAULT NULL,
            DCUVERS INT DEFAULT NULL,
            DCUSYSID VARCHAR(8) DEFAULT NULL,
            DCUTMSTP VARCHAR(16) DEFAULT NULL,
            DCUTIME TIME DEFAULT NULL,
            DCUDATE VARCHAR(8) DEFAULT NULL,
            DCUOUTH_LEN INT DEFAULT NULL,
            DBCDATA INT DEFAULT NULL,
            DBCUSER VARCHAR(8) DEFAULT NULL,
            DBCDATE VARCHAR(10) DEFAULT NULL,
            DBCTIME TIME DEFAULT NULL,
            DBCDESC VARCHAR(255) DEFAULT NULL,
            DBCFLAGS INT DEFAULT NULL,
            DBCFLGDC INT DEFAULT NULL,
            DBCDEFMC VARCHAR(8) DEFAULT NULL,
            DBCMCLEN INT DEFAULT NULL,
            DBCMCNAM VARCHAR(8) DEFAULT NULL,
            DBCTRKSZ INT DEFAULT NULL,
            DBCCYLCP INT DEFAULT NULL,
            DBCDUNIT VARCHAR(8) DEFAULT NULL,
            DBCSRST VARCHAR(100) DEFAULT NULL,
            DBCSTAT INT DEFAULT NULL,
            DBCFSYSN_1 VARCHAR(8) DEFAULT NULL, DBCFSYSN_2 VARCHAR(8) DEFAULT NULL, DBCFSYSN_3 VARCHAR(8) DEFAULT NULL, DBCFSYSN_4 VARCHAR(8) DEFAULT NULL, DBCFSYSN_5 VARCHAR(8) DEFAULT NULL, DBCFSYSN_6 VARCHAR(8) DEFAULT NULL, DBCFSYSN_7 VARCHAR(8) DEFAULT NULL, DBCFSYSN_8 VARCHAR(8) DEFAULT NULL,
            DBCSCDSN VARCHAR(255) DEFAULT NULL,
            DBCSFEAT_1 INT DEFAULT NULL, DBCSFEAT_2 INT DEFAULT NULL, DBCSFEAT_3 INT DEFAULT NULL, DBCSFEAT_4 INT DEFAULT NULL, DBCSFEAT_5 INT DEFAULT NULL, DBCSFEAT_6 INT DEFAULT NULL, DBCSFEAT_7 INT DEFAULT NULL, DBCSFEAT_8 INT DEFAULT NULL,
            DBCSYSNT_1 INT DEFAULT NULL, DBCSYSNT_2 INT DEFAULT NULL, DBCSYSNT_3 INT DEFAULT NULL, DBCSYSNT_4 INT DEFAULT NULL, DBCSYSNT_5 INT DEFAULT NULL, DBCSYSNT_6 INT DEFAULT NULL, DBCSYSNT_7 INT DEFAULT NULL, DBCSYSNT_8 INT DEFAULT NULL,
            DBCSYSNM_1 VARCHAR(8) DEFAULT NULL, DBCSYSNM_2 VARCHAR(8) DEFAULT NULL, DBCSYSNM_3 VARCHAR(8) DEFAULT NULL, DBCSYSNM_4 VARCHAR(8) DEFAULT NULL, DBCSYSNM_5 VARCHAR(8) DEFAULT NULL, DBCSYSNM_6 VARCHAR(8) DEFAULT NULL, DBCSYSNM_7 VARCHAR(8) DEFAULT NULL, DBCSYSNM_8 VARCHAR(8) DEFAULT NULL, DBCSYSNM_9 VARCHAR(8) DEFAULT NULL, DBCSYSNM_10 VARCHAR(8) DEFAULT NULL, DBCSYSNM_11 VARCHAR(8) DEFAULT NULL, DBCSYSNM_12 VARCHAR(8) DEFAULT NULL, DBCSYSNM_13 VARCHAR(8) DEFAULT NULL, DBCSYSNM_14 VARCHAR(8) DEFAULT NULL, DBCSYSNM_15 VARCHAR(8) DEFAULT NULL, DBCSYSNM_16 VARCHAR(8) DEFAULT NULL, DBCSYSNM_17 VARCHAR(8) DEFAULT NULL, DBCSYSNM_18 VARCHAR(8) DEFAULT NULL, DBCSYSNM_19 VARCHAR(8) DEFAULT NULL, DBCSYSNM_20 VARCHAR(8) DEFAULT NULL, DBCSYSNM_21 VARCHAR(8) DEFAULT NULL, DBCSYSNM_22 VARCHAR(8) DEFAULT NULL, DBCSYSNM_23 VARCHAR(8) DEFAULT NULL, DBCSYSNM_24 VARCHAR(8) DEFAULT NULL, DBCSYSNM_25 VARCHAR(8) DEFAULT NULL, DBCSYSNM_26 VARCHAR(8) DEFAULT NULL, DBCSYSNM_27 VARCHAR(8) DEFAULT NULL, DBCSYSNM_28 VARCHAR(8) DEFAULT NULL, DBCSYSNM_29 VARCHAR(8) DEFAULT NULL, DBCSYSNM_30 VARCHAR(8) DEFAULT NULL, DBCSYSNM_31 VARCHAR(8) DEFAULT NULL, DBCSYSNM_32 VARCHAR(8) DEFAULT NULL,
            DBCSYSFT_1 INT DEFAULT NULL, DBCSYSFT_2 INT DEFAULT NULL, DBCSYSFT_3 INT DEFAULT NULL, DBCSYSFT_4 INT DEFAULT NULL, DBCSYSFT_5 INT DEFAULT NULL, DBCSYSFT_6 INT DEFAULT NULL, DBCSYSFT_7 INT DEFAULT NULL, DBCSYSFT_8 INT DEFAULT NULL, DBCSYSFT_9 INT DEFAULT NULL, DBCSYSFT_10 INT DEFAULT NULL, DBCSYSFT_11 INT DEFAULT NULL, DBCSYSFT_12 INT DEFAULT NULL, DBCSYSFT_13 INT DEFAULT NULL, DBCSYSFT_14 INT DEFAULT NULL, DBCSYSFT_15 INT DEFAULT NULL, DBCSYSFT_16 INT DEFAULT NULL, DBCSYSFT_17 INT DEFAULT NULL, DBCSYSFT_18 INT DEFAULT NULL, DBCSYSFT_19 INT DEFAULT NULL, DBCSYSFT_20 INT DEFAULT NULL, DBCSYSFT_21 INT DEFAULT NULL, DBCSYSFT_22 INT DEFAULT NULL, DBCSYSFT_23 INT DEFAULT NULL, DBCSYSFT_24 INT DEFAULT NULL, DBCSYSFT_25 INT DEFAULT NULL, DBCSYSFT_26 INT DEFAULT NULL, DBCSYSFT_27 INT DEFAULT NULL, DBCSYSFT_28 INT DEFAULT NULL, DBCSYSFT_29 INT DEFAULT NULL, DBCSYSFT_30 INT DEFAULT NULL, DBCSYSFT_31 INT DEFAULT NULL, DBCSYSFT_32 INT DEFAULT NULL,
            DBCSNMTY_1 INT DEFAULT NULL, DBCSNMTY_2 INT DEFAULT NULL, DBCSNMTY_3 INT DEFAULT NULL, DBCSNMTY_4 INT DEFAULT NULL, DBCSNMTY_5 INT DEFAULT NULL, DBCSNMTY_6 INT DEFAULT NULL, DBCSNMTY_7 INT DEFAULT NULL, DBCSNMTY_8 INT DEFAULT NULL, DBCSNMTY_9 INT DEFAULT NULL, DBCSNMTY_10 INT DEFAULT NULL, DBCSNMTY_11 INT DEFAULT NULL, DBCSNMTY_12 INT DEFAULT NULL, DBCSNMTY_13 INT DEFAULT NULL, DBCSNMTY_14 INT DEFAULT NULL, DBCSNMTY_15 INT DEFAULT NULL, DBCSNMTY_16 INT DEFAULT NULL, DBCSNMTY_17 INT DEFAULT NULL, DBCSNMTY_18 INT DEFAULT NULL, DBCSNMTY_19 INT DEFAULT NULL, DBCSNMTY_20 INT DEFAULT NULL, DBCSNMTY_21 INT DEFAULT NULL, DBCSNMTY_22 INT DEFAULT NULL, DBCSNMTY_23 INT DEFAULT NULL, DBCSNMTY_24 INT DEFAULT NULL, DBCSNMTY_25 INT DEFAULT NULL, DBCSNMTY_26 INT DEFAULT NULL, DBCSNMTY_27 INT DEFAULT NULL, DBCSNMTY_28 INT DEFAULT NULL, DBCSNMTY_29 INT DEFAULT NULL, DBCSNMTY_30 INT DEFAULT NULL, DBCSNMTY_31 INT DEFAULT NULL, DBCSNMTY_32 INT DEFAULT NULL,
            DBCSEPNL INT DEFAULT NULL,
            DBCSEPNM INT DEFAULT NULL
        )`,
        `CREATE TABLE IF NOT EXISTS dcollect_c (
            id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
            TIMESTAMP DATETIME DEFAULT NULL,
            DCUOUTH INT DEFAULT NULL,
            DCURDW BIGINT DEFAULT NULL,
            DCULENG INT DEFAULT NULL,
            DCUVERS1 INT DEFAULT NULL,
            DCUVERS2 INT DEFAULT NULL,
            DCUVERSC INT DEFAULT NULL,
            DCUBCVER INT DEFAULT NULL,
            DCUSGVER INT DEFAULT NULL,
            DCURCTYP CHAR(2) DEFAULT NULL,
            DCUVERS INT DEFAULT NULL,
            DCUSYSID VARCHAR(8) DEFAULT NULL,
            DCUTMSTP VARCHAR(16) DEFAULT NULL,
            DCUTIME TIME DEFAULT NULL,
            DCUDATE VARCHAR(8) DEFAULT NULL,
            DCUOUTH_LEN INT DEFAULT NULL,
            UCAFOCC INT DEFAULT NULL,
            UCBFOCC INT DEFAULT NULL,
            UCCOLDT VARCHAR(8) DEFAULT NULL,
            UCCAPDE INT DEFAULT NULL,
            UCFLAG1 INT DEFAULT NULL,
            UCINTVM INT DEFAULT NULL,
            UCNOMIG INT DEFAULT NULL,
            UCNINTV INT DEFAULT NULL,
            UCTOTAL BIGINT DEFAULT NULL,
            UCTGOCC INT DEFAULT NULL,
            UCTROCC INT DEFAULT NULL,
            UCVOLSR VARCHAR(8) DEFAULT NULL
        )`,
        `CREATE TABLE IF NOT EXISTS dcollect_d (
            id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
            TIMESTAMP DATETIME DEFAULT NULL,
            DCUOUTH INT DEFAULT NULL,
            DCURDW BIGINT DEFAULT NULL,
            DCULENG INT DEFAULT NULL,
            DCUVERS1 INT DEFAULT NULL,
            DCUVERS2 INT DEFAULT NULL,
            DCUVERSC INT DEFAULT NULL,
            DCUBCVER INT DEFAULT NULL,
            DCUSGVER INT DEFAULT NULL,
            DCURCTYP CHAR(2) DEFAULT NULL,
            DCUVERS INT DEFAULT NULL,
            DCUSYSID VARCHAR(8) DEFAULT NULL,
            DCUTMSTP VARCHAR(16) DEFAULT NULL,
            DCUTIME TIME DEFAULT NULL,
            DCUDATE VARCHAR(8) DEFAULT NULL,
            DCUOUTH_LEN INT DEFAULT NULL,
            DCDADSI INT DEFAULT NULL,
            DCDDSNAM VARCHAR(255) DEFAULT NULL,
            DCDERROR INT DEFAULT NULL,
            DCDFLAG1 INT DEFAULT NULL,
            DCDFLAG2 INT DEFAULT NULL,
            DCDFLAG3 INT DEFAULT NULL,
            DCDDSOR0_1 INT DEFAULT NULL,
            DCDDSOR1_1 INT DEFAULT NULL,
            DCDRECRD INT DEFAULT NULL,
            DCDNMEXT INT DEFAULT NULL,
            DCDVOLSR VARCHAR(8) DEFAULT NULL,
            DCDBKLNG INT DEFAULT NULL,
            DCDLRECL INT DEFAULT NULL,
            DCDALLSP INT DEFAULT NULL,
            DCDUSESP INT DEFAULT NULL,
            DCDSCALL INT DEFAULT NULL,
            DCDNMBLK INT DEFAULT NULL,
            DCDCREDT VARCHAR(8) DEFAULT NULL,
            DCDEXPDT VARCHAR(8) DEFAULT NULL,
            DCDLSTRF VARCHAR(8) DEFAULT NULL,
            DCDDSSER VARCHAR(8) DEFAULT NULL,
            DCDVOLSQ VARCHAR(8) DEFAULT NULL,
            DCDLBKDT VARCHAR(8) DEFAULT NULL,
            DCDDCLAS VARCHAR(32) DEFAULT NULL,
            DCDDCLNG INT DEFAULT NULL,
            DCDDATCL VARCHAR(32) DEFAULT NULL,
            DCDSCLAS VARCHAR(32) DEFAULT NULL,
            DCDSCLNG INT DEFAULT NULL,
            DCDSTGCL VARCHAR(32) DEFAULT NULL,
            DCDMCLAS VARCHAR(32) DEFAULT NULL,
            DCDMCLNG INT DEFAULT NULL,
            DCDMGTCL VARCHAR(32) DEFAULT NULL,
            DCDSTOGP VARCHAR(32) DEFAULT NULL,
            DCDSGLNG INT DEFAULT NULL,
            DCDSTGRP VARCHAR(32) DEFAULT NULL,
            DCDCCSID VARCHAR(8) DEFAULT NULL,
            DCDCATF INT DEFAULT NULL,
            DCDDSCBF INT DEFAULT NULL,
            DCDUDSIZ VARCHAR(100) DEFAULT NULL,
            DCDCUDSZ VARCHAR(100) DEFAULT NULL,
            DCDEXFLG INT DEFAULT NULL,
            DCDSCNT INT DEFAULT NULL,
            DCDOVERA INT DEFAULT NULL,
            DCDACCT VARCHAR(32) DEFAULT NULL,
            DCDFLAG5 INT DEFAULT NULL,
            DCDDS9F1 INT DEFAULT NULL,
            DCDJBNMC VARCHAR(8) DEFAULT NULL,
            DCDSTNMC VARCHAR(8) DEFAULT NULL,
            DCDTIMEC INT DEFAULT NULL,
            DCDALLSX INT DEFAULT NULL,
            DCDUSESX INT DEFAULT NULL,
            DCDSCALX INT DEFAULT NULL,
            DCDNMBLX INT DEFAULT NULL,
            DCDXPSEV INT DEFAULT NULL,
            DCDCTYPE VARCHAR(255) DEFAULT NULL,
            DCDAENCR VARCHAR(255) DEFAULT NULL,
            DCDATYPE VARCHAR(255) DEFAULT NULL,
            DCDAKLBL VARCHAR(255) DEFAULT NULL,
            DCDADSIE INT DEFAULT NULL
        )`,
        `CREATE TABLE IF NOT EXISTS dcollect_dc (
            id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
            TIMESTAMP DATETIME DEFAULT NULL,
            DCUOUTH INT DEFAULT NULL,
            DCURDW BIGINT DEFAULT NULL,
            DCULENG INT DEFAULT NULL,
            DCUVERS1 INT DEFAULT NULL,
            DCUVERS2 INT DEFAULT NULL,
            DCUVERSC INT DEFAULT NULL,
            DCUBCVER INT DEFAULT NULL,
            DCUSGVER INT DEFAULT NULL,
            DCURCTYP CHAR(2) DEFAULT NULL,
            DCUVERS INT DEFAULT NULL,
            DCUSYSID VARCHAR(8) DEFAULT NULL,
            DCUTMSTP VARCHAR(16) DEFAULT NULL,
            DCUTIME TIME DEFAULT NULL,
            DCUDATE VARCHAR(8) DEFAULT NULL,
            DCUOUTH_LEN INT DEFAULT NULL,
            DDCDATA INT DEFAULT NULL,
            DDCNMFLD VARCHAR(8) DEFAULT NULL,
            DDCNMLEN INT DEFAULT NULL,
            DDCNAME VARCHAR(8) DEFAULT NULL,
            DDCUSER VARCHAR(8) DEFAULT NULL,
            DDCDATE VARCHAR(10) DEFAULT NULL,
            DDCTIME TIME DEFAULT NULL,
            DDCDESC VARCHAR(255) DEFAULT NULL,
            DDCSPEC1_1 INT DEFAULT NULL, DDCSPEC2_1 INT DEFAULT NULL, DDCSPEC3_1 INT DEFAULT NULL, DDCSPEC4_1 INT DEFAULT NULL,
            DDCRCORG INT DEFAULT NULL, DDCRECFM INT DEFAULT NULL, DDCDSFLG INT DEFAULT NULL, DDCCNTL INT DEFAULT NULL, DDCRETPD INT DEFAULT NULL, DDCEXPYR INT DEFAULT NULL, DDCEXPDY INT DEFAULT NULL, DDCVOLCT INT DEFAULT NULL, DDCDSNTY INT DEFAULT NULL, DDCSPPRI INT DEFAULT NULL, DDCSPSEC INT DEFAULT NULL, DDCDIBLK INT DEFAULT NULL, DDCAVREC INT DEFAULT NULL, DDCREDUC INT DEFAULT NULL, DDCRBIAS INT DEFAULT NULL, DDCDVC INT DEFAULT NULL, DDCAUNIT INT DEFAULT NULL, DDCLRECL INT DEFAULT NULL, DDCCISZ INT DEFAULT NULL, DDCFRSP VARCHAR(8) DEFAULT NULL, DDCCIPCT INT DEFAULT NULL, DDCCAPCT INT DEFAULT NULL, DDCSHROP INT DEFAULT NULL, DDCXREG INT DEFAULT NULL, DDCXSYS INT DEFAULT NULL, DDCVINDX INT DEFAULT NULL, DDCKLEN INT DEFAULT NULL, DDCKOFF INT DEFAULT NULL, DDCCAMT INT DEFAULT NULL, DDCCOMP INT DEFAULT NULL, DDCMEDIA INT DEFAULT NULL, DDCRECTE INT DEFAULT NULL,
            DDCRLS1 VARCHAR(100) DEFAULT NULL, DDCBWOTP INT DEFAULT NULL, DDCLOGRC INT DEFAULT NULL, DDCSPAND INT DEFAULT NULL, DDCFRLOG INT DEFAULT NULL,
            DDCLOGNM VARCHAR(100) DEFAULT NULL, DDCLOGLN INT DEFAULT NULL, DDCLOGID VARCHAR(100) DEFAULT NULL,
            DDCSPECA INT DEFAULT NULL, DDCSPECB INT DEFAULT NULL, DDCSPECC INT DEFAULT NULL, DDCSPECD INT DEFAULT NULL, DDCSFLG INT DEFAULT NULL, DDCVSAM1 INT DEFAULT NULL, DDCVBYT1 INT DEFAULT NULL, DDCEATTR INT DEFAULT NULL, DDCCT INT DEFAULT NULL, DDCDSCF INT DEFAULT NULL, DDCRBYTE INT DEFAULT NULL, DDCBLKLM INT DEFAULT NULL, DDCBSZLM INT DEFAULT NULL, DDCTAPE1 INT DEFAULT NULL, DDCPSCA INT DEFAULT NULL, DDCPSEG INT DEFAULT NULL,
            DDCVSP VARCHAR(100) DEFAULT NULL, DDCVSPU VARCHAR(100) DEFAULT NULL, DDCVSPV VARCHAR(100) DEFAULT NULL,
            DDCKYLB1 VARCHAR(100) DEFAULT NULL, DDCKLBL1 VARCHAR(100) DEFAULT NULL, DDCKLBN1 VARCHAR(100) DEFAULT NULL, DDCKYCD1 VARCHAR(100) DEFAULT NULL,
            DDCKYLB2 VARCHAR(100) DEFAULT NULL, DDCKLBL2 VARCHAR(100) DEFAULT NULL, DDCKLBN2 VARCHAR(100) DEFAULT NULL, DDCKYCD2 VARCHAR(100) DEFAULT NULL,
            DDCRMODE VARCHAR(100) DEFAULT NULL, DDCDKYLB VARCHAR(100) DEFAULT NULL, DDCDKLBL VARCHAR(100) DEFAULT NULL, DDCDKLBN VARCHAR(100) DEFAULT NULL,
            DDCDATAE INT DEFAULT NULL
        )`,
        `CREATE TABLE IF NOT EXISTS dcollect_lb (
            id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
            TIMESTAMP DATETIME DEFAULT NULL,
            DCUOUTH INT DEFAULT NULL,
            DCURDW BIGINT DEFAULT NULL,
            DCULENG INT DEFAULT NULL,
            DCUVERS1 INT DEFAULT NULL,
            DCUVERS2 INT DEFAULT NULL,
            DCUVERSC INT DEFAULT NULL,
            DCUBCVER INT DEFAULT NULL,
            DCUSGVER INT DEFAULT NULL,
            DCURCTYP CHAR(2) DEFAULT NULL,
            DCUVERS INT DEFAULT NULL,
            DCUSYSID VARCHAR(8) DEFAULT NULL,
            DCUTMSTP VARCHAR(16) DEFAULT NULL,
            DCUTIME TIME DEFAULT NULL,
            DCUDATE VARCHAR(8) DEFAULT NULL,
            DCUOUTH_LEN INT DEFAULT NULL,
            DLBDATA INT DEFAULT NULL,
            DLBNMFLD VARCHAR(8) DEFAULT NULL,
            DLBNMLEN INT DEFAULT NULL,
            DLBLNAME VARCHAR(8) DEFAULT NULL,
            DLBNAME VARCHAR(8) DEFAULT NULL,
            DLBDUSER VARCHAR(8) DEFAULT NULL,
            DLBDDATE VARCHAR(10) DEFAULT NULL,
            DLBFLAGS INT DEFAULT NULL,
            DLBDTIME TIME DEFAULT NULL,
            DLBOMST_1 VARCHAR(8) DEFAULT NULL, DLBOMST_2 VARCHAR(8) DEFAULT NULL, DLBOMST_3 VARCHAR(8) DEFAULT NULL, DLBOMST_4 VARCHAR(8) DEFAULT NULL, DLBOMST_5 VARCHAR(8) DEFAULT NULL, DLBOMST_6 VARCHAR(8) DEFAULT NULL, DLBOMST_7 VARCHAR(8) DEFAULT NULL, DLBOMST_8 VARCHAR(8) DEFAULT NULL,
            DLBSOUT_1 INT DEFAULT NULL, DLBSOUT_2 INT DEFAULT NULL, DLBSOUT_3 INT DEFAULT NULL, DLBSOUT_4 INT DEFAULT NULL, DLBSOUT_5 INT DEFAULT NULL, DLBSOUT_6 INT DEFAULT NULL, DLBSOUT_7 INT DEFAULT NULL, DLBSOUT_8 INT DEFAULT NULL,
            DLBCFCS_1 INT DEFAULT NULL, DLBCFCS_2 INT DEFAULT NULL, DLBCFCS_3 INT DEFAULT NULL, DLBCFCS_4 INT DEFAULT NULL, DLBCFCS_5 INT DEFAULT NULL, DLBCFCS_6 INT DEFAULT NULL, DLBCFCS_7 INT DEFAULT NULL, DLBCFCS_8 INT DEFAULT NULL,
            DLBTYPE INT DEFAULT NULL, DLBDTYPE INT DEFAULT NULL, DLBDCONS INT DEFAULT NULL, DLBEDVT INT DEFAULT NULL, DLBEJD INT DEFAULT NULL,
            DLBLCBID VARCHAR(8) DEFAULT NULL, DLBEDUNM VARCHAR(100) DEFAULT NULL, DLBDEFDC VARCHAR(8) DEFAULT NULL,
            DLBDCLEN INT DEFAULT NULL, DLBDCLNM VARCHAR(8) DEFAULT NULL, DLBDCNAM VARCHAR(8) DEFAULT NULL,
            DLBREQST_1 INT DEFAULT NULL, DLBREQST_2 INT DEFAULT NULL, DLBREQST_3 INT DEFAULT NULL, DLBREQST_4 INT DEFAULT NULL, DLBREQST_5 INT DEFAULT NULL, DLBREQST_6 INT DEFAULT NULL, DLBREQST_7 INT DEFAULT NULL, DLBREQST_8 INT DEFAULT NULL, DLBREQST_9 INT DEFAULT NULL, DLBREQST_10 INT DEFAULT NULL, DLBREQST_11 INT DEFAULT NULL, DLBREQST_12 INT DEFAULT NULL, DLBREQST_13 INT DEFAULT NULL, DLBREQST_14 INT DEFAULT NULL, DLBREQST_15 INT DEFAULT NULL, DLBREQST_16 INT DEFAULT NULL, DLBREQST_17 INT DEFAULT NULL, DLBREQST_18 INT DEFAULT NULL, DLBREQST_19 INT DEFAULT NULL, DLBREQST_20 INT DEFAULT NULL, DLBREQST_21 INT DEFAULT NULL, DLBREQST_22 INT DEFAULT NULL, DLBREQST_23 INT DEFAULT NULL, DLBREQST_24 INT DEFAULT NULL, DLBREQST_25 INT DEFAULT NULL, DLBREQST_26 INT DEFAULT NULL, DLBREQST_27 INT DEFAULT NULL, DLBREQST_28 INT DEFAULT NULL, DLBREQST_29 INT DEFAULT NULL, DLBREQST_30 INT DEFAULT NULL, DLBREQST_31 INT DEFAULT NULL, DLBREQST_32 INT DEFAULT NULL,
            DLBCURST_1 INT DEFAULT NULL, DLBCURST_2 INT DEFAULT NULL, DLBCURST_3 INT DEFAULT NULL, DLBCURST_4 INT DEFAULT NULL, DLBCURST_5 INT DEFAULT NULL, DLBCURST_6 INT DEFAULT NULL, DLBCURST_7 INT DEFAULT NULL, DLBCURST_8 INT DEFAULT NULL, DLBCURST_9 INT DEFAULT NULL, DLBCURST_10 INT DEFAULT NULL, DLBCURST_11 INT DEFAULT NULL, DLBCURST_12 INT DEFAULT NULL, DLBCURST_13 INT DEFAULT NULL, DLBCURST_14 INT DEFAULT NULL, DLBCURST_15 INT DEFAULT NULL, DLBCURST_16 INT DEFAULT NULL, DLBCURST_17 INT DEFAULT NULL, DLBCURST_18 INT DEFAULT NULL, DLBCURST_19 INT DEFAULT NULL, DLBCURST_20 INT DEFAULT NULL, DLBCURST_21 INT DEFAULT NULL, DLBCURST_22 INT DEFAULT NULL, DLBCURST_23 INT DEFAULT NULL, DLBCURST_24 INT DEFAULT NULL, DLBCURST_25 INT DEFAULT NULL, DLBCURST_26 INT DEFAULT NULL, DLBCURST_27 INT DEFAULT NULL, DLBCURST_28 INT DEFAULT NULL, DLBCURST_29 INT DEFAULT NULL, DLBCURST_30 INT DEFAULT NULL, DLBCURST_31 INT DEFAULT NULL, DLBCURST_32 INT DEFAULT NULL
        )`,
        `CREATE TABLE IF NOT EXISTS dcollect_m (
            id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
            TIMESTAMP DATETIME DEFAULT NULL,
            DCUOUTH INT DEFAULT NULL,
            DCURDW BIGINT DEFAULT NULL,
            DCULENG INT DEFAULT NULL,
            DCUVERS1 INT DEFAULT NULL,
            DCUVERS2 INT DEFAULT NULL,
            DCUVERSC INT DEFAULT NULL,
            DCUBCVER INT DEFAULT NULL,
            DCUSGVER INT DEFAULT NULL,
            DCURCTYP CHAR(2) DEFAULT NULL,
            DCUVERS INT DEFAULT NULL,
            DCUSYSID VARCHAR(8) DEFAULT NULL,
            DCUTMSTP VARCHAR(16) DEFAULT NULL,
            DCUTIME TIME DEFAULT NULL,
            DCUDATE VARCHAR(8) DEFAULT NULL,
            DCUOUTH_LEN INT DEFAULT NULL,
            UM_USER_DATASIZE BIGINT DEFAULT NULL,
            UM_COMP_DATASIZE BIGINT DEFAULT NULL,
            UM_CLD_INFO INT DEFAULT NULL,
            UM_CLOUD_NAME_LENGTH INT DEFAULT NULL,
            UM_CLOUD_NAME VARCHAR(255) DEFAULT NULL,
            UM_CONTAINER_NAME VARCHAR(255) DEFAULT NULL,
            UM_OBJ_NUMBER INT DEFAULT NULL,
            UM_CLD_COMP_PERCENT INT DEFAULT NULL,
            UMALLSP INT DEFAULT NULL,
            UMBKLNG INT DEFAULT NULL,
            UMCREDT VARCHAR(8) DEFAULT NULL,
            UMDSNAM VARCHAR(255) DEFAULT NULL,
            UMDEVCL CHAR(1) DEFAULT NULL,
            UMDSORG INT DEFAULT NULL,
            UMDSIZE INT DEFAULT NULL,
            UMDATE VARCHAR(8) DEFAULT NULL,
            UMDCLAS VARCHAR(32) DEFAULT NULL,
            UMDCLNG INT DEFAULT NULL,
            UMDATCL VARCHAR(32) DEFAULT NULL,
            UMEXPDT VARCHAR(8) DEFAULT NULL,
            UMENCRPT INT DEFAULT NULL,
            UMENCRPL VARCHAR(255) DEFAULT NULL,
            UMFLAG1 INT DEFAULT NULL,
            UMFLAG2 INT DEFAULT NULL,
            UMFRVOL VARCHAR(8) DEFAULT NULL,
            UMFLAG3 INT DEFAULT NULL,
            UMFLAG4 INT DEFAULT NULL,
            UMLRFDT VARCHAR(8) DEFAULT NULL,
            UMMCLAS VARCHAR(32) DEFAULT NULL,
            UMMCLNG INT DEFAULT NULL,
            UMMGTCL VARCHAR(32) DEFAULT NULL,
            UMMDSIE INT DEFAULT NULL,
            UMNMIG INT DEFAULT NULL,
            UMPDSEV INT DEFAULT NULL,
            UMRECOR INT DEFAULT NULL,
            UMRECSP INT DEFAULT NULL,
            UMSCLNG INT DEFAULT NULL,
            UMSTGCL VARCHAR(32) DEFAULT NULL,
            UMUSESP INT DEFAULT NULL
        )`,
        `CREATE TABLE IF NOT EXISTS dcollect_mc (
            id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
            TIMESTAMP DATETIME DEFAULT NULL,
            DCUOUTH INT DEFAULT NULL,
            DCURDW BIGINT DEFAULT NULL,
            DCULENG INT DEFAULT NULL,
            DCUVERS1 INT DEFAULT NULL,
            DCUVERS2 INT DEFAULT NULL,
            DCUVERSC INT DEFAULT NULL,
            DCUBCVER INT DEFAULT NULL,
            DCUSGVER INT DEFAULT NULL,
            DCURCTYP CHAR(2) DEFAULT NULL,
            DCUVERS INT DEFAULT NULL,
            DCUSYSID VARCHAR(8) DEFAULT NULL,
            DCUTMSTP VARCHAR(16) DEFAULT NULL,
            DCUTIME TIME DEFAULT NULL,
            DCUDATE VARCHAR(8) DEFAULT NULL,
            DCUOUTH_LEN INT DEFAULT NULL,
            DMCDATA INT DEFAULT NULL,
            DMCNMLEN INT DEFAULT NULL,
            DMCNAME VARCHAR(8) DEFAULT NULL,
            DMCUSER VARCHAR(8) DEFAULT NULL,
            DMCDATE VARCHAR(10) DEFAULT NULL,
            DMCTIME TIME DEFAULT NULL,
            DMCDESC VARCHAR(255) DEFAULT NULL,
            DMCSPEC1 INT DEFAULT NULL,
            DMCSPEC2 INT DEFAULT NULL,
            DMCRLF INT DEFAULT NULL,
            DMCGDGFL INT DEFAULT NULL,
            DMCPELEM INT DEFAULT NULL,
            DMCEXPF INT DEFAULT NULL,
            DMCEXPAC INT DEFAULT NULL,
            DMCRDARC INT DEFAULT NULL,
            DMCRETF INT DEFAULT NULL,
            DMCRFMT INT DEFAULT NULL,
            DMCEXPDY INT DEFAULT NULL,
            DMCEXDAT INT DEFAULT NULL,
            DMCEYEAR INT DEFAULT NULL,
            DMCEDAY INT DEFAULT NULL,
            DMCMIGF INT DEFAULT NULL,
            DMCPRDY INT DEFAULT NULL,
            DMCL1DY INT DEFAULT NULL,
            DMCCMAU INT DEFAULT NULL,
            DMCBKFLG INT DEFAULT NULL,
            DMCBKFQ INT DEFAULT NULL,
            DMCBKVS INT DEFAULT NULL,
            DMCBVRD INT DEFAULT NULL,
            DMCBKDY INT DEFAULT NULL,
            DMCBKNP INT DEFAULT NULL,
            DMCBADU INT DEFAULT NULL,
            DMCCPYTC INT DEFAULT NULL,
            DMCBKUDC INT DEFAULT NULL,
            DMCMRETF INT DEFAULT NULL,
            DMCMRTDY INT DEFAULT NULL,
            DMCTSCR INT DEFAULT NULL,
            DMCTSLU INT DEFAULT NULL,
            DMCPERD INT DEFAULT NULL,
            DMCVSCR INT DEFAULT NULL,
            DMCVSCY INT DEFAULT NULL,
            DMCVSCM INT DEFAULT NULL,
            DMCVSCD INT DEFAULT NULL,
            DMCVSLU INT DEFAULT NULL,
            DMCVSUY INT DEFAULT NULL,
            DMCVSUM INT DEFAULT NULL,
            DMCVSUD INT DEFAULT NULL,
            DMCVPRD INT DEFAULT NULL,
            DMCVPMD INT DEFAULT NULL,
            DMCVPQT INT DEFAULT NULL,
            DMCVPQD INT DEFAULT NULL,
            DMCVPQM INT DEFAULT NULL,
            DMCVPYR INT DEFAULT NULL,
            DMCVPYD INT DEFAULT NULL,
            DMCVPYM INT DEFAULT NULL,
            DMCCTSRL INT DEFAULT NULL,
            DMCCTCPY INT DEFAULT NULL,
            DMCCL2DY INT DEFAULT NULL,
            DMCCLOUD INT DEFAULT NULL,
            DMCCLLEN INT DEFAULT NULL,
            DMCCLNAM VARCHAR(255) DEFAULT NULL,
            DMCSZLTE INT DEFAULT NULL,
            DMCSZGT INT DEFAULT NULL,
            DMCACLTE INT DEFAULT NULL,
            DMCACGT INT DEFAULT NULL,
            DMCDATAE INT DEFAULT NULL
        )`,
        `CREATE TABLE IF NOT EXISTS dcollect_sc (
            id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
            TIMESTAMP DATETIME DEFAULT NULL,
            DCUOUTH INT DEFAULT NULL,
            DCURDW BIGINT DEFAULT NULL,
            DCULENG INT DEFAULT NULL,
            DCUVERS1 INT DEFAULT NULL,
            DCUVERS2 INT DEFAULT NULL,
            DCUVERSC INT DEFAULT NULL,
            DCUBCVER INT DEFAULT NULL,
            DCUSGVER INT DEFAULT NULL,
            DCURCTYP CHAR(2) DEFAULT NULL,
            DCUVERS INT DEFAULT NULL,
            DCUSYSID VARCHAR(8) DEFAULT NULL,
            DCUTMSTP VARCHAR(16) DEFAULT NULL,
            DCUTIME TIME DEFAULT NULL,
            DCUDATE VARCHAR(8) DEFAULT NULL,
            DCUOUTH_LEN INT DEFAULT NULL,
            DSCDATA INT DEFAULT NULL,
            DSCNMFLD VARCHAR(8) DEFAULT NULL,
            DSCNMLEN INT DEFAULT NULL,
            DSCNAME VARCHAR(8) DEFAULT NULL,
            DSCUSER VARCHAR(8) DEFAULT NULL,
            DSCDATE VARCHAR(10) DEFAULT NULL,
            DSCTIME TIME DEFAULT NULL,
            DSCDESC VARCHAR(255) DEFAULT NULL,
            DSCFLAGS INT DEFAULT NULL,
            DSCFLAG2 INT DEFAULT NULL,
            DSCVERSN INT DEFAULT NULL,
            DSCBAKUP INT DEFAULT NULL,
            DSCAVAIL INT DEFAULT NULL,
            DSCDIRB INT DEFAULT NULL,
            DSCSEQB INT DEFAULT NULL,
            DSCACCES INT DEFAULT NULL,
            DSCIACDL INT DEFAULT NULL,
            DSCDIRR INT DEFAULT NULL,
            DSCSEQR INT DEFAULT NULL,
            DSCSTSDR INT DEFAULT NULL,
            DSCCCHST VARCHAR(100) DEFAULT NULL,
            DSCCSLEN INT DEFAULT NULL,
            DSCCSNAM VARCHAR(100) DEFAULT NULL,
            DSCDIRCW INT DEFAULT NULL,
            DSCSEQCW INT DEFAULT NULL,
            DSCPAV INT DEFAULT NULL,
            DSCSTOSL INT DEFAULT NULL,
            DSCVFLG2 INT DEFAULT NULL,
            DSCCMMFT INT DEFAULT NULL,
            DSCDATAE INT DEFAULT NULL
        )`,
        `CREATE TABLE IF NOT EXISTS dcollect_sg (
            id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
            TIMESTAMP DATETIME DEFAULT NULL,
            DCUOUTH INT DEFAULT NULL,
            DCURDW BIGINT DEFAULT NULL,
            DCULENG INT DEFAULT NULL,
            DCUVERS1 INT DEFAULT NULL,
            DCUVERS2 INT DEFAULT NULL,
            DCUVERSC INT DEFAULT NULL,
            DCUBCVER INT DEFAULT NULL,
            DCUSGVER INT DEFAULT NULL,
            DCURCTYP CHAR(2) DEFAULT NULL,
            DCUVERS INT DEFAULT NULL,
            DCUSYSID VARCHAR(8) DEFAULT NULL,
            DCUTMSTP VARCHAR(16) DEFAULT NULL,
            DCUTIME TIME DEFAULT NULL,
            DCUDATE VARCHAR(8) DEFAULT NULL,
            DCUOUTH_LEN INT DEFAULT NULL,
            DSGDATA INT DEFAULT NULL,
            DSGNMFLD VARCHAR(8) DEFAULT NULL,
            DSGNMLEN INT DEFAULT NULL,
            DSGNAME VARCHAR(8) DEFAULT NULL,
            DSGUSER VARCHAR(8) DEFAULT NULL,
            DSGDATE VARCHAR(10) DEFAULT NULL,
            DSGTIME TIME DEFAULT NULL,
            DSGDESC VARCHAR(255) DEFAULT NULL,
            DSGFLAGS INT DEFAULT NULL,
            DSGFLGDC INT DEFAULT NULL,
            DSGFTYPE INT DEFAULT NULL,
            DSGFHTHR INT DEFAULT NULL,
            DSGFLTHR INT DEFAULT NULL,
            DSGFVMAX INT DEFAULT NULL,
            DSGFVUNT VARCHAR(8) DEFAULT NULL,
            DSGDMPCL_1 VARCHAR(100) DEFAULT NULL, DSGDMPCL_2 VARCHAR(100) DEFAULT NULL, DSGDMPCL_3 VARCHAR(100) DEFAULT NULL, DSGDMPCL_4 VARCHAR(100) DEFAULT NULL, DSGDMPCL_5 VARCHAR(100) DEFAULT NULL,
            DSGSTAT_1 INT DEFAULT NULL, DSGSTAT_2 INT DEFAULT NULL, DSGSTAT_3 INT DEFAULT NULL, DSGSTAT_4 INT DEFAULT NULL, DSGSTAT_5 INT DEFAULT NULL, DSGSTAT_6 INT DEFAULT NULL, DSGSTAT_7 INT DEFAULT NULL, DSGSTAT_8 INT DEFAULT NULL,
            DSGABSYS VARCHAR(8) DEFAULT NULL, DSGADSYS VARCHAR(8) DEFAULT NULL, DSGAMSYS VARCHAR(8) DEFAULT NULL,
            DSGCSMSS_1 INT DEFAULT NULL, DSGCSMSS_2 INT DEFAULT NULL, DSGCSMSS_3 INT DEFAULT NULL, DSGCSMSS_4 INT DEFAULT NULL, DSGCSMSS_5 INT DEFAULT NULL, DSGCSMSS_6 INT DEFAULT NULL, DSGCSMSS_7 INT DEFAULT NULL, DSGCSMSS_8 INT DEFAULT NULL,
            DSGGBKUF INT DEFAULT NULL, DSGTBLGR VARCHAR(100) DEFAULT NULL, DSGOAMFL INT DEFAULT NULL, DSGCYLST INT DEFAULT NULL, DSGCYLED INT DEFAULT NULL, DSGVOLFT INT DEFAULT NULL, DSGDRVST INT DEFAULT NULL,
            DSGOLBNL_1 INT DEFAULT NULL, DSGOLBNL_2 INT DEFAULT NULL, DSGOLBNL_3 INT DEFAULT NULL, DSGOLBNL_4 INT DEFAULT NULL, DSGOLBNL_5 INT DEFAULT NULL, DSGOLBNL_6 INT DEFAULT NULL, DSGOLBNL_7 INT DEFAULT NULL, DSGOLBNL_8 INT DEFAULT NULL,
            DSGOLBNM_1 VARCHAR(8) DEFAULT NULL, DSGOLBNM_2 VARCHAR(8) DEFAULT NULL, DSGOLBNM_3 VARCHAR(8) DEFAULT NULL, DSGOLBNM_4 VARCHAR(8) DEFAULT NULL, DSGOLBNM_5 VARCHAR(8) DEFAULT NULL, DSGOLBNM_6 VARCHAR(8) DEFAULT NULL, DSGOLBNM_7 VARCHAR(8) DEFAULT NULL, DSGOLBNM_8 VARCHAR(8) DEFAULT NULL,
            DSGSYSST INT DEFAULT NULL, DSGCNSMS INT DEFAULT NULL, DSGOFLOW INT DEFAULT NULL, DSGEXNLN INT DEFAULT NULL,
            DSGEXNM VARCHAR(100) DEFAULT NULL, DSGFLAG2 INT DEFAULT NULL, DSGSBKPT INT DEFAULT NULL, DSGSHTHR INT DEFAULT NULL, DSGSLTHR INT DEFAULT NULL, DSGRERV INT DEFAULT NULL, DSGTOTAP INT DEFAULT NULL, DSGTMSAP INT DEFAULT NULL,
            DSGOAMID VARCHAR(100) DEFAULT NULL, DSGDATAE INT DEFAULT NULL
        )`,
        `CREATE TABLE IF NOT EXISTS dcollect_t (
            id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
            TIMESTAMP DATETIME DEFAULT NULL,
            DCUOUTH INT DEFAULT NULL,
            DCURDW BIGINT DEFAULT NULL,
            DCULENG INT DEFAULT NULL,
            DCUVERS1 INT DEFAULT NULL,
            DCUVERS2 INT DEFAULT NULL,
            DCUVERSC INT DEFAULT NULL,
            DCUBCVER INT DEFAULT NULL,
            DCUSGVER INT DEFAULT NULL,
            DCURCTYP CHAR(2) DEFAULT NULL,
            DCUVERS INT DEFAULT NULL,
            DCUSYSID VARCHAR(8) DEFAULT NULL,
            DCUTMSTP VARCHAR(16) DEFAULT NULL,
            DCUTIME TIME DEFAULT NULL,
            DCUDATE VARCHAR(8) DEFAULT NULL,
            DCUOUTH_LEN INT DEFAULT NULL,
            UTCAPTE INT DEFAULT NULL,
            UTEMPTY INT DEFAULT NULL,
            UTFULL INT DEFAULT NULL,
            UTILP INT DEFAULT NULL,
            UTPART INT DEFAULT NULL,
            UTSTYPE CHAR(1) DEFAULT NULL
        )`,
        `CREATE TABLE IF NOT EXISTS dcollect_v (
            id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
            TIMESTAMP DATETIME DEFAULT NULL,
            DCUOUTH INT DEFAULT NULL,
            DCURDW BIGINT DEFAULT NULL,
            DCULENG INT DEFAULT NULL,
            DCUVERS1 INT DEFAULT NULL,
            DCUVERS2 INT DEFAULT NULL,
            DCUVERSC INT DEFAULT NULL,
            DCUBCVER INT DEFAULT NULL,
            DCUSGVER INT DEFAULT NULL,
            DCURCTYP CHAR(2) DEFAULT NULL,
            DCUVERS INT DEFAULT NULL,
            DCUSYSID VARCHAR(8) DEFAULT NULL,
            DCUTMSTP VARCHAR(16) DEFAULT NULL,
            DCUTIME TIME DEFAULT NULL,
            DCUDATE VARCHAR(8) DEFAULT NULL,
            DCUOUTH_LEN INT DEFAULT NULL,
            DCVVOLI INT DEFAULT NULL,
            DCVVOLSR VARCHAR(8) DEFAULT NULL,
            DCVFLAG1 INT DEFAULT NULL,
            DCVERROR INT DEFAULT NULL,
            DCVPERCT INT DEFAULT NULL,
            DCVFRESP BIGINT DEFAULT NULL,
            DCVALLOC BIGINT DEFAULT NULL,
            DCVVLCAP BIGINT DEFAULT NULL,
            DCVFRAGI INT DEFAULT NULL,
            DCVLGEXT BIGINT DEFAULT NULL,
            DCVFREXT INT DEFAULT NULL,
            DCVFDSCB INT DEFAULT NULL,
            DCVFVIRS INT DEFAULT NULL,
            DCVDVTYP VARCHAR(8) DEFAULT NULL,
            DCVDVNUM INT DEFAULT NULL,
            DCVSTGGP VARCHAR(32) DEFAULT NULL,
            DCVSGLNG INT DEFAULT NULL,
            DCVSGTCL VARCHAR(32) DEFAULT NULL,
            DCVDPTYP VARCHAR(8) DEFAULT NULL,
            DCVTRPCT INT DEFAULT NULL,
            DCVEAVOL_1 BIGINT DEFAULT NULL,
            DCVEAVOL_2 BIGINT DEFAULT NULL,
            DCVEAVOL_3 BIGINT DEFAULT NULL,
            DCVTRFSP BIGINT DEFAULT NULL,
            DCVTRALC BIGINT DEFAULT NULL,
            DCVTRVLC BIGINT DEFAULT NULL,
            DCVTRFRG BIGINT DEFAULT NULL,
            DCVTRLGE INT DEFAULT NULL,
            DCVTRFRX INT DEFAULT NULL,
            DCVFCYLS INT DEFAULT NULL,
            DCVFTRKS INT DEFAULT NULL,
            DCVVOLIE INT DEFAULT NULL
        )`,
        `CREATE TABLE IF NOT EXISTS dcollect_vl (
            id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
            TIMESTAMP DATETIME DEFAULT NULL,
            DCUOUTH INT DEFAULT NULL,
            DCURDW BIGINT DEFAULT NULL,
            DCULENG INT DEFAULT NULL,
            DCUVERS1 INT DEFAULT NULL,
            DCUVERS2 INT DEFAULT NULL,
            DCUVERSC INT DEFAULT NULL,
            DCUBCVER INT DEFAULT NULL,
            DCUSGVER INT DEFAULT NULL,
            DCURCTYP CHAR(2) DEFAULT NULL,
            DCUVERS INT DEFAULT NULL,
            DCUSYSID VARCHAR(8) DEFAULT NULL,
            DCUTMSTP VARCHAR(16) DEFAULT NULL,
            DCUTIME TIME DEFAULT NULL,
            DCUDATE VARCHAR(8) DEFAULT NULL,
            DCUOUTH_LEN INT DEFAULT NULL,
            DVLDATA INT DEFAULT NULL,
            DVLNMLEN INT DEFAULT NULL,
            DVLVSER VARCHAR(8) DEFAULT NULL,
            DVLUSER VARCHAR(8) DEFAULT NULL,
            DVLDATE VARCHAR(10) DEFAULT NULL,
            DVLTIME TIME DEFAULT NULL,
            DVLFLGDC INT DEFAULT NULL,
            DVLSGLEN INT DEFAULT NULL,
            DVLSTGRP VARCHAR(8) DEFAULT NULL,
            DVLSMSS_1 INT DEFAULT NULL, DVLSMSS_2 INT DEFAULT NULL, DVLSMSS_3 INT DEFAULT NULL, DVLSMSS_4 INT DEFAULT NULL, DVLSMSS_5 INT DEFAULT NULL, DVLSMSS_6 INT DEFAULT NULL, DVLSMSS_7 INT DEFAULT NULL, DVLSMSS_8 INT DEFAULT NULL,
            DVLMVSS_1 INT DEFAULT NULL, DVLMVSS_2 INT DEFAULT NULL, DVLMVSS_3 INT DEFAULT NULL, DVLMVSS_4 INT DEFAULT NULL, DVLMVSS_5 INT DEFAULT NULL, DVLMVSS_6 INT DEFAULT NULL, DVLMVSS_7 INT DEFAULT NULL, DVLMVSS_8 INT DEFAULT NULL,
            DVLCSMSS_1 INT DEFAULT NULL, DVLCSMSS_2 INT DEFAULT NULL, DVLCSMSS_3 INT DEFAULT NULL, DVLCSMSS_4 INT DEFAULT NULL, DVLCSMSS_5 INT DEFAULT NULL, DVLCSMSS_6 INT DEFAULT NULL, DVLCSMSS_7 INT DEFAULT NULL, DVLCSMSS_8 INT DEFAULT NULL,
            DVLNUCBA INT DEFAULT NULL, DVLNTCPY INT DEFAULT NULL, DVLNFREE INT DEFAULT NULL, DVLNLEXT INT DEFAULT NULL, DVLN0CNT INT DEFAULT NULL, DVLTRKSZ INT DEFAULT NULL, DVLNLEVL INT DEFAULT NULL,
            DVLSTSMS_1 INT DEFAULT NULL, DVLSTSMS_2 INT DEFAULT NULL, DVLSTSMS_3 INT DEFAULT NULL, DVLSTSMS_4 INT DEFAULT NULL, DVLSTSMS_5 INT DEFAULT NULL, DVLSTSMS_6 INT DEFAULT NULL, DVLSTSMS_7 INT DEFAULT NULL, DVLSTSMS_8 INT DEFAULT NULL, DVLSTSMS_9 INT DEFAULT NULL, DVLSTSMS_10 INT DEFAULT NULL, DVLSTSMS_11 INT DEFAULT NULL, DVLSTSMS_12 INT DEFAULT NULL, DVLSTSMS_13 INT DEFAULT NULL, DVLSTSMS_14 INT DEFAULT NULL, DVLSTSMS_15 INT DEFAULT NULL, DVLSTSMS_16 INT DEFAULT NULL, DVLSTSMS_17 INT DEFAULT NULL, DVLSTSMS_18 INT DEFAULT NULL, DVLSTSMS_19 INT DEFAULT NULL, DVLSTSMS_20 INT DEFAULT NULL, DVLSTSMS_21 INT DEFAULT NULL, DVLSTSMS_22 INT DEFAULT NULL, DVLSTSMS_23 INT DEFAULT NULL, DVLSTSMS_24 INT DEFAULT NULL, DVLSTSMS_25 INT DEFAULT NULL, DVLSTSMS_26 INT DEFAULT NULL, DVLSTSMS_27 INT DEFAULT NULL, DVLSTSMS_28 INT DEFAULT NULL, DVLSTSMS_29 INT DEFAULT NULL, DVLSTSMS_30 INT DEFAULT NULL, DVLSTSMS_31 INT DEFAULT NULL, DVLSTSMS_32 INT DEFAULT NULL,
            DVLSTMVS_1 INT DEFAULT NULL, DVLSTMVS_2 INT DEFAULT NULL, DVLSTMVS_3 INT DEFAULT NULL, DVLSTMVS_4 INT DEFAULT NULL, DVLSTMVS_5 INT DEFAULT NULL, DVLSTMVS_6 INT DEFAULT NULL, DVLSTMVS_7 INT DEFAULT NULL, DVLSTMVS_8 INT DEFAULT NULL, DVLSTMVS_9 INT DEFAULT NULL, DVLSTMVS_10 INT DEFAULT NULL, DVLSTMVS_11 INT DEFAULT NULL, DVLSTMVS_12 INT DEFAULT NULL, DVLSTMVS_13 INT DEFAULT NULL, DVLSTMVS_14 INT DEFAULT NULL, DVLSTMVS_15 INT DEFAULT NULL, DVLSTMVS_16 INT DEFAULT NULL, DVLSTMVS_17 INT DEFAULT NULL, DVLSTMVS_18 INT DEFAULT NULL, DVLSTMVS_19 INT DEFAULT NULL, DVLSTMVS_20 INT DEFAULT NULL, DVLSTMVS_21 INT DEFAULT NULL, DVLSTMVS_22 INT DEFAULT NULL, DVLSTMVS_23 INT DEFAULT NULL, DVLSTMVS_24 INT DEFAULT NULL, DVLSTMVS_25 INT DEFAULT NULL, DVLSTMVS_26 INT DEFAULT NULL, DVLSTMVS_27 INT DEFAULT NULL, DVLSTMVS_28 INT DEFAULT NULL, DVLSTMVS_29 INT DEFAULT NULL, DVLSTMVS_30 INT DEFAULT NULL, DVLSTMVS_31 INT DEFAULT NULL, DVLSTMVS_32 INT DEFAULT NULL,
            DVLCNSMS_1 INT DEFAULT NULL, DVLCNSMS_2 INT DEFAULT NULL, DVLCNSMS_3 INT DEFAULT NULL, DVLCNSMS_4 INT DEFAULT NULL, DVLCNSMS_5 INT DEFAULT NULL, DVLCNSMS_6 INT DEFAULT NULL, DVLCNSMS_7 INT DEFAULT NULL, DVLCNSMS_8 INT DEFAULT NULL, DVLCNSMS_9 INT DEFAULT NULL, DVLCNSMS_10 INT DEFAULT NULL, DVLCNSMS_11 INT DEFAULT NULL, DVLCNSMS_12 INT DEFAULT NULL, DVLCNSMS_13 INT DEFAULT NULL, DVLCNSMS_14 INT DEFAULT NULL, DVLCNSMS_15 INT DEFAULT NULL, DVLCNSMS_16 INT DEFAULT NULL, DVLCNSMS_17 INT DEFAULT NULL, DVLCNSMS_18 INT DEFAULT NULL, DVLCNSMS_19 INT DEFAULT NULL, DVLCNSMS_20 INT DEFAULT NULL, DVLCNSMS_21 INT DEFAULT NULL, DVLCNSMS_22 INT DEFAULT NULL, DVLCNSMS_23 INT DEFAULT NULL, DVLCNSMS_24 INT DEFAULT NULL, DVLCNSMS_25 INT DEFAULT NULL, DVLCNSMS_26 INT DEFAULT NULL, DVLCNSMS_27 INT DEFAULT NULL, DVLCNSMS_28 INT DEFAULT NULL, DVLCNSMS_29 INT DEFAULT NULL, DVLCNSMS_30 INT DEFAULT NULL, DVLCNSMS_31 INT DEFAULT NULL, DVLCNSMS_32 INT DEFAULT NULL,
            DVLTRKCP INT DEFAULT NULL, DVLTRKFR INT DEFAULT NULL, DVLTRKEX INT DEFAULT NULL, DVLDATAE INT DEFAULT NULL
        )`
    ];

    for (const query of createTableQueries) {
        try {
            await connection.query(query);
            console.log('Successfully executed table creation query');
        } catch (error) {
            console.error('Error creating table:', error);
            throw error;
        }
    }

    // Verify tables were created
    const [tablesAfter] = await connection.query('SHOW TABLES');
    const existingTablesAfter = tablesAfter.map(t => Object.values(t)[0]);
    console.log('Tables after creation:', existingTablesAfter);
}

function promisifyFtpCommand(ftpClient, command, ...args) {
    return new Promise((resolve, reject) => {
        ftpClient[command](...args, function(err, result) {
            if (err) reject(err);
            else resolve(result);
        });
    });
}

async function loadDataFromFTPToMySQL(ftpClient, mysqlConnection, remotePath, tableName, columns) {
    return new Promise((resolve, reject) => {
        ftpClient.get(remotePath, async (err, readStream) => {
            if (err) {
                console.error(`Error getting file ${remotePath}:`, err);
                reject(err);
                return;
            }

            console.log(`Started processing file: ${remotePath}`);

            const passthroughStream = new stream.PassThrough();
            readStream.pipe(passthroughStream);

            const sql = `
                SET NAMES utf8mb4;
                SET CHARACTER SET utf8mb4;
                SET character_set_connection=utf8mb4;
                SET SESSION sql_mode = '';
                
                LOAD DATA LOCAL INFILE 'stdin' 
                INTO TABLE ${tableName}
                CHARACTER SET utf8mb4
                FIELDS TERMINATED BY ',' 
                OPTIONALLY ENCLOSED BY '"' 
                LINES TERMINATED BY '\\n' 
                IGNORE 1 LINES
                (${columns.join(', ')})
            `;

            try {
                await mysqlConnection.query("SET NAMES utf8mb4");
                const [result] = await mysqlConnection.query({
                    sql: sql,
                    infileStreamFactory: () => passthroughStream
                });
                
                const [rows] = await mysqlConnection.query(`SELECT ROW_COUNT() as count`);
                const affectedRows = rows[0].count;
                
                console.log(`Data loaded into ${tableName}: ${affectedRows} rows affected`);
                resolve(result);
            } catch (error) {
                console.error(`Error loading data into ${tableName}:`, error);
                reject(error);
            }
        });
    });
}

async function checkForNewFiles(ftpClient, mysqlConnection, startDate, endDate, lpar, metrics) {
    console.log(`Checking for new files for ${lpar} from ${startDate} to ${endDate || 'now'}`);
    
    try {
        const visitedDirs = await new Promise((resolve, reject) => {
            dcolJSONcontroller.readLparData(lpar, (err, data) => {
                if (err) reject(err);
                else resolve(data);
            });
        });
        
        await promisifyFtpCommand(ftpClient, 'cwd', config.dds[lpar].dcol.ftp.directory);
        const list = await promisifyFtpCommand(ftpClient, 'list');

        const startDateTime = new Date(startDate);
        const endDateTime = endDate ? new Date(endDate) : new Date();

        const newDirs = list.filter(function(item) {
            if (item.type !== 'd') return false;
            const dirDate = parseDirName(item.name);
            if (!dirDate) return false;
            
            
            // Check if directory exists in memory and if all requested metrics are processed.
            const dirInfo = visitedDirs[item.name];
            const needsProcessing = !dirInfo || 
                                  !dirInfo.processedMetrics || 
                                  metrics.some(metric => !dirInfo.processedMetrics.includes(metric));

            // Only include directory if it needs processing and is within the date range.
            return needsProcessing && dirDate >= startDateTime && dirDate <= endDateTime;
        });

        console.log(`Found ${newDirs.length} directories to process for ${lpar}`);

        for (const dir of newDirs) {
            const fullPath = path.join(config.dds[lpar].dcol.ftp.directory, dir.name);
            try {
                // Get existing processed metrics for this directory.
                const existingDirInfo = visitedDirs[dir.name] || {};
                const existingProcessedMetrics = existingDirInfo.processedMetrics || [];

                // Only process metrics that haven't been processed yet for this run.
                const metricsToProcess = metrics.filter(metric => 
                    !existingProcessedMetrics.includes(metric)
                );

                if (metricsToProcess.length > 0) {
                    console.log(`Processing directory ${dir.name} for metrics:`, metricsToProcess);
                   
                    const processedMetrics = await processDirectory(ftpClient, mysqlConnection, fullPath, lpar, metricsToProcess);
                    const dirDate = parseDirName(dir.name);

                    // Combine existing and newly processed metrics, ensuring no duplicates.
                    const allProcessedMetrics = [...new Set([...existingProcessedMetrics, ...processedMetrics])];
                    
                    
                    const updateData = {
                        [dir.name]: {
                            timestamp: dirDate.toISOString(),
                            processedMetrics: allProcessedMetrics
                        }
                    };
                    
                    await new Promise((resolve, reject) => {
                        dcolJSONcontroller.updateLparData(lpar, updateData, (updateErr, updatedData) => {
                            if (updateErr) reject(updateErr);
                            else {
                                console.log(`Processed and updated ${lpar}.json with ${dir.name}, metrics: ${processedMetrics.join(', ')}`);
                                resolve(updatedData);
                            }
                        });
                    });
                } else {
                    console.log(`Skipping directory ${dir.name} - all requested metrics already processed.`);
                }
            } catch (error) {
                console.error('Error processing directory ' + dir.name + ' for ' + lpar + ':', error);
            }
        }
        
        console.log(`Finished processing ${newDirs.length} directories for ${lpar}`);
        return newDirs.length;
    } catch (error) {
        console.error('Error in checkForNewFiles:', error);
        throw error;
    }
}

async function processDirectory(ftpClient, mysqlConnection, dirPath, lpar, metrics) {
    console.log(`Processing directory: ${dirPath}`);
    const processedMetrics = []; 
    
    try {
        await promisifyFtpCommand(ftpClient, 'cwd', dirPath);
        const files = await promisifyFtpCommand(ftpClient, 'list');

        for (const file of files) {
            if (file.type === '-' && file.name.endsWith('.csv')) {
                const tableName = getTableNameFromFileName(file.name);
                // The metrics array now contains only the metrics we need to process for this specific run.
                if (tableName && metrics.includes(tableName)) {
                    try {
                        await loadDataFromFTPToMySQL(
                            ftpClient,
                            mysqlConnection,
                            file.name,
                            tableName,
                            tableHeaders[tableName]
                        );
                      
                        processedMetrics.push(tableName);
                        console.log(`Successfully processed metric ${tableName} from ${file.name}`);
                    } catch (error) {
                        console.error(`Error processing ${file.name}:`, error);
                    }
                }
            }
        }
    } catch (error) {
        console.error(`Error processing directory ${dirPath}:`, error);
    } finally {
        try {
            await promisifyFtpCommand(ftpClient, 'cwd', config.dds[lpar].dcol.ftp.directory);
        } catch (error) {
            console.error(`Error changing back to base directory:`, error);
        }
    }
    
    return processedMetrics; 
}

async function startDCOL(req, res) {
    const { startDate, endDate, lpar, metrics, continuousMonitoring } = req.body;
    console.log(`startDCOL called with params:`, { startDate, endDate, lpar, metrics, continuousMonitoring });

    if (runningProcesses[lpar] && runningProcesses[lpar].isRunning) {
        return res.status(400).json({ success: false, message: `DCOL process is already running for ${lpar}` });
    }

    runningProcesses[lpar] = { 
        isRunning: true, 
        continuousMonitoring: continuousMonitoring,
        startDate: startDate,
        endDate: continuousMonitoring ? null : endDate
    };

    let mysqlConnection;
    let ftpClient;
    let databaseCreated = false;

    try {
        // Create MySQL connection without database specified
        mysqlConnection = await mysql.createConnection({
            host: config.dds[lpar].dcol.mysql.host,
            user: config.dds[lpar].dcol.mysql.user,
            password: config.dds[lpar].dcol.mysql.password,
            multipleStatements: true
        });
        console.log('MySQL connection established');

        // Check if database exists
        const [rows] = await mysqlConnection.query(`SHOW DATABASES LIKE '${lpar}'`);
        if (rows.length === 0) {
            // Create database
            await mysqlConnection.query(`CREATE DATABASE ${lpar}`);
            databaseCreated = true;
            console.log(`Database ${lpar} created`);
        } else {
            console.log(`Database ${lpar} already exists`);
        }

        // Use the database
        await mysqlConnection.query(`USE ${lpar}`);
        console.log(`Using database ${lpar}`);

        // Always create tables if they don't exist
        await createTables(mysqlConnection);
        console.log('Ensured tables exist');

        // Initialize or get DCOL memory
        const visitedDirs = await new Promise((resolve, reject) => {
            dcolJSONcontroller.readLparData(lpar, (err, data) => {
                if (err) {
                    // If error reading, initialize empty memory
                    dcolJSONcontroller.writeLparData(lpar, {}, (writeErr) => {
                        if (writeErr) reject(writeErr);
                        else resolve({});
                    });
                } else {
                    resolve(data || {});
                }
            });
        });
        console.log('DCOL memory initialized/loaded');

        // Start FTP connection
        ftpClient = new FTP();
        await new Promise((resolve, reject) => {
            ftpClient.on('ready', () => {
                console.log('FTP connection established');
                resolve();
            });
            ftpClient.on('error', reject);
            ftpClient.connect({
                host: config.dds[lpar].ddsbaseurl,
                user: config.dds[lpar].ddsuser,
                password: config.dds[lpar].ddspwd,
            });
        });

        console.log('Starting to check for new files');
        if (continuousMonitoring) {
            await checkForNewFiles(ftpClient, mysqlConnection, startDate, null, lpar, metrics);
            startContinuousMonitoring(lpar, metrics);
        } else {
            await checkForNewFiles(ftpClient, mysqlConnection, startDate, endDate, lpar, metrics);
            runningProcesses[lpar].isRunning = false;
        }
        console.log('Finished checking for new files');

        res.json({ 
            success: true, 
            message: continuousMonitoring ? 'DCOL process started and running continuously' : 'DCOL process completed successfully',
            databaseCreated: databaseCreated
        });
    } catch (error) {
        console.error('Error in startDCOL:', error);
        delete runningProcesses[lpar];
        res.status(500).json({ success: false, message: 'Error in DCOL process', error: error.message });
    } finally {
        if (!continuousMonitoring) {
            if (mysqlConnection) {
                try {
                    await mysqlConnection.end();
                    console.log('MySQL connection closed.');
                } catch (err) {
                    console.error('Error closing MySQL connection:', err);
                }
            }
            if (ftpClient && ftpClient.connected) {
                ftpClient.end();
                console.log('FTP connection closed.');
            }
        }
    }
}

// Add enforceDataRetention function with hardcoded 1-day retention
async function enforceDataRetention(connection, lpar) {
    try {
        const retentionDays = 1; // Hardcoded 1-day retention
        const tables = ['dcollect_a', 'dcollect_ai', 'dcollect_bc', 'dcollect_d', 
                       'dcollect_dc', 'dcollect_lb', 'dcollect_mc', 'dcollect_sc', 
                       'dcollect_sg', 'dcollect_v', 'dcollect_vl'];

        for (const table of tables) {
            const deleteQuery = `DELETE FROM ${table} 
                               WHERE timestamp < DATE_SUB(NOW(), INTERVAL ${retentionDays} DAY)`;
            await connection.query(deleteQuery);
            console.log(`Applied ${retentionDays} day retention policy for ${table} in ${lpar}`);
        }
    } catch (error) {
        console.error('Error enforcing DCOL data retention:', error);
        throw error;
    }
}

// Update startContinuousMonitoring function
function startContinuousMonitoring(lpar, metrics) {
    const checkIntervalMinutes = parseInt(config.dds[lpar].dcol.checkInterval);
    console.log(`Setting up continuous monitoring for ${lpar} with interval of ${checkIntervalMinutes} minutes`);

    monitoringIntervals[lpar] = setInterval(async () => {
        let mysqlConnection;
        let ftpClient;

        try {
            // ADD THE SETUP CODE HERE

            const visitedDirs = await new Promise((resolve, reject) => {
                dcolJSONController.readLparData(lpar, (err, data) => {
                    if (err) reject(err);
                    else resolve(data);
                });
            });

            const lastProcessedDate = Object.keys(visitedDirs).length > 0
                ? new Date(Math.max(...Object.values(visitedDirs).map(d => new Date(d))))
                : runningProcesses[lpar].startDate;

            await checkForNewFiles(ftpClient, mysqlConnection, lastProcessedDate, null, lpar, metrics);
            await enforceDataRetention(mysqlConnection, lpar);

        } catch (error) {
            console.error(`Error in continuous monitoring for ${lpar}:`, error);
        } finally {
            if (mysqlConnection) await mysqlConnection.end();
            if (ftpClient) ftpClient.end();
        }
    }, checkIntervalMinutes * 60000); // Convert minutes to milliseconds
}

async function clearDatabase(req, res) {
    const { lpar } = req.body;
    const mysqlConfig = {
        ...config.dds[lpar].dcol.mysql,
        database: lpar,
    };

    let connection;
    try {
        connection = await mysql.createConnection(mysqlConfig);

        const tables = ['dcollect_a', 'dcollect_ai', 'dcollect_bc', 'dcollect_d', 'dcollect_dc', 
                       'dcollect_lb', 'dcollect_mc', 'dcollect_sc', 'dcollect_sg', 'dcollect_v', 'dcollect_vl'];
        for (const table of tables) {
            await connection.query(`TRUNCATE TABLE ${table}`);
        }

        await new Promise((resolve, reject) => {
            dcolJSONcontroller.writeLparData(lpar, {}, (err) => {
                if (err) reject(err);
                else resolve();
            });
        });

        if (runningProcesses[lpar]) {
            delete runningProcesses[lpar];
        }

        res.json({ success: true, message: `All tables in database ${lpar} and DCOL memory cleared successfully` });
    } catch (error) {
        console.error('Error clearing database and DCOL memory:', error);
        res.json({ success: false, message: 'Failed to clear database and DCOL memory: ' + error.message });
    } finally {
        if (connection) await connection.end();
    }
}

function stopContinuousMonitoring(req, res) {
    const { lpar } = req.body;
    console.log(`Attempting to stop DCOL process for ${lpar}`);

    if (runningProcesses[lpar]) {
        if (monitoringIntervals[lpar]) {
            clearInterval(monitoringIntervals[lpar]);
            delete monitoringIntervals[lpar];
        }

        if (runningProcesses[lpar].mysqlConnection) {
            runningProcesses[lpar].mysqlConnection.end();
        }

        if (runningProcesses[lpar].ftpClient) {
            runningProcesses[lpar].ftpClient.end();
        }

        delete runningProcesses[lpar];
        res.json({ success: true, message: `Stopped DCOL process for ${lpar}` });
    } else {
        res.status(400).json({ success: false, message: `No active DCOL process for ${lpar}` });
    }
}

function getRunningProcesses(req, res) {
    const runningProcessesInfo = {};
    for (const lpar in runningProcesses) {
        runningProcessesInfo[lpar] = {
            isRunning: runningProcesses[lpar].isRunning,
            continuousMonitoring: runningProcesses[lpar].continuousMonitoring
        };
    }
    res.json(runningProcessesInfo);
}

module.exports = {
    startDCOL,
    clearDatabase,
    stopContinuousMonitoring,
    getRunningProcesses
};
