module.exports.dds = { //please modify this object with your DDS server details
    LPAR1: {
        "ddshhttptype":"https",
        "ddsbaseurl":"salis.com",
        "ddsbaseport":"0808",
        "ddsauth":"true",
        "ddsuser":"user",
        "ddspwd":"pass",
        "rmf3filename":"rmfm3.xml",
        "rmfppfilename":"rmfpp.xml",
        "mvsResource":",RPRT,MVS_IMAGE",
        "PCI": 2951,
        "usePrometheus":"false",
        "rmf3interval":"100",
        "appurl":"localhost",
        "appport":"3090",
        "httptype":"https",
    },
    LPAR1 : {
        "ddshhttptype":"https",
        "ddsbaseurl":"salis.com",
        "ddsbaseport":"0808",
        "ddsauth":"true",
        "ddsuser":"user",
        "ddspwd":"pass",
        "rmf3filename":"rmfm3.xml",
        "rmfppfilename":"rmfpp.xml",
        "mvsResource":",RPRT,MVS_IMAGE",
        "PCI": 2951,
        "usePrometheus":"false",
        "rmf3interval":"100",
        "appurl":"localhost",
        "appport":"3090",
        "httptype":"https",
    }
}