module.exports.dds = { //please modify this object with your DDS server details
    LPAR1: {
        "ddshhttptype":"https",
        "ddsbaseurl":"salis.com",
        "ddsbaseport":"4595",
        "ddsauth":"true",
        "ddsuser":"user",
        "ddspwd":"pass",
        "rmf3filename":"rmfm3.xml",
        "rmfppfilename":"rmfpp.xml",
        "mvsResource":",RPRT,MVS_IMAGE",
        "PCI": 2951,
        "usePrometheus":"true",
        "useMongo":"false",
    },
    LPAR2 : {
        "ddshhttptype":"https",
        "ddsbaseurl":"salis.com",
        "ddsbaseport":"4595",
        "ddsauth":"true",
        "ddsuser":"user",
        "ddspwd":"pass",
        "rmf3filename":"rmfm3.xml",
        "rmfppfilename":"rmfpp.xml",
        "mvsResource":",RPRT,MVS_IMAGE",
        "PCI": 2951,
        "usePrometheus":"true",
        "useMongo":"false",
    }
}