module.exports = {
    REPORTS: {
        RMFPP: [
            "CACHE",
            "CHAN",
            "CPU",
            "CRYPTO",
            "DEVICE",
            "EADM",
            "HFS",
            "IOQ",
            "OMVS",
            "PAGESP",
            "PAGING",
            "SDELAY",
            "VSTOR",
            "XCF",
            "CF",
            "WLMGL"
        ],
        RMFM3: [
            "CHANNEL",
            "CPC",
            "DELAY",
            "DEV",
            "DEVR",
            "DSND",
            "EADM",
            "ENCLAVE",
            "ENQ",
            "HSM",
            "JES",
            "OPD",
            "PROC",
            "PROCU",
            "STOR",
            "STORC",
            "STORCR",
            "STORM",
            "SYSINFO",
            "USAGE"
        ]
    },
    REPORTTYPE:{
        CACHDET: "SYSPLEX",
        CACHSUM: "SYSPLEX",
        CFACT: "SYSPLEX",
        CFOVER: "SYSPLEX",
        CFSYS: "SYSPLEX",
        CHANNEL: "MVS_IMAGE",
        CPC: "MVS_IMAGE",
        CRYPTO: "SYSPLEX",
        DELAY: "MVS_IMAGE",
        DEV: "MVS_IMAGE",
        DEVR: "MVS_IMAGE",
        DI: "SYSPLEX",
        DSND: "MVS_IMAGE",
        DSNJ: "SYSPLEX",
        DSNV: "SYSPLEX",
        EADM: "MVS_IMAGE",
        ENCLAVE: "MVS_IMAGE",
        ENQ: "MVS_IMAGE",
        ENQR: "SYSPLEX",
        HSM: "MVS_IMAGE",
        IOQUEUE: "SYSPLEX",
        JES: "MVS_IMAGE",
        JOB: "SYSPLEX",
        LOCKSP: "SYSPLEX",
        LOCKSU: "SYSPLEX",
        OPD: "MVS_IMAGE",
        PCIE: "SYSPLEX",
        PROC: "MVS_IMAGE",
        PROCU: "MVS_IMAGE",
        RLSDS: "SYSPLEX",
        RLSLRU: "SYSPLEX",
        RLSSC: "SYSPLEX",
        SPACED: "SYSPLEX",
        SPACEG: "SYSPLEX",
        STOR: "MVS_IMAGE",
        STORC: "MVS_IMAGE",
        STORCR: "MVS_IMAGE",
        STORF: "MVS_IMAGE",
        STORM: "MVS_IMAGE",
        STORR: "MVS_IMAGE",
        STORS: "MVS_IMAGE",
        SYSENQ: "SYSPLEX",
        SYSINFO: "MVS_IMAGE",
        SYSRG: "SYSPLEX",
        SYSRTD: "SYSPLEX",
        SYSSUM: "SYSPLEX",
        SYSWKM: "SYSPLEX",
        USAGE: "MVS_IMAGE",
        WFEX: "SYSPLEX",
        XCF: "SYSPLEX",
        ZFSFS: "SYSPLEX",
        ZFSKN: "SYSPLEX",
        ZFSOVW: "SYSPLEX"
    },
    
    METRICDESCRIPTIONS: {
        CHACPIVC: { description: "CHANNEL - Path ID", type: "id" },
        CHACPNVC: { description: "CHANNEL - Number of DCM-managed channels", type: "nbr" },
        CHACGVC: { description: "CHANNEL - Type generation", type: "type" },
        CHACPTVC: { description: "CHANNEL - Path type", type: "type" },
        CHACSIVC: { description: "CHANNEL - Shared indication", type: "status" },
        CHACPUVC: { description: "CHANNEL - Partition utilization %", type: "nbr" },
        CHACTUVC: { description: "CHANNEL - Total utilization %", type: "nbr" },
        CHACTBVC: { description: "CHANNEL - Bus utilization %", type: "nbr" },
        CHACPRVC: { description: "CHANNEL - Partition transfer rate (Read) in B/sec", type: "nbr" },
        CHACTRVC: { description: "CHANNEL - Total transfer rate (Read) in B/sec", type: "nbr" },
        CHACPWVC: { description: "CHANNEL - Partition transfer rate (Write) in B/sec", type: "nbr" },
        CHACTWVC: { description: "CHANNEL - Total transfer rate (Write) in B/sec", type: "nbr" },
        CHACPMVC: { description: "CHANNEL - Partition message sent rate", type: "nbr" },
        CHACTMVC: { description: "CHANNEL - Total message sent rate", type: "nbr" },
        CHACPSVC: { description: "CHANNEL - Partition message sent size", type: "nbr" },
        CHACTSVC: { description: "CHANNEL - Total message sent size", type: "nbr" },
        CHACSFVC: { description: "CHANNEL - Partition message sent fail rate", type: "nbr" },
        CHACPFVC: { description: "CHANNEL - Partition message receive fail rate", type: "nbr" },
        CHACTFVC: { description: "CHANNEL - Total message receive fail rate", type: "nbr" },
        CHACFRTE: { description: "CHANNEL - Rate of native FICON ops", type: "nbr" },
        CHACFACT: { description: "CHANNEL - Average number of native FICON operations concurrently active", type: "nbr" },
        CHACXRTE: { description: "CHANNEL - Rate of High Performance FICON (zHPF) operations", type: "nbr" },
        CHACXACT: { description: "CHANNEL - Average number of zHPF operations concurrently active", type: "nbr" },
        CHACFDFR: { description: "CHANNEL - Number of deferred native FICON operations per second", type: "nbr" },
        CHACXDFR: { description: "CHANNEL - Number of deferred zHPF operations per second", type: "nbr" },
        CHACLTVC: { description: "CHANNEL - Logical channel type", type: "type" },
        CHACMGVC: { description: "CHANNEL - Message rate", type: "nbr" },
        CHACNET1: { description: "CHANNEL - Physical-network identifier (PNET ID) of first channel path port", type: "id" },
        CHACNET2: { description: "CHANNEL - Physical-network identifier (PNET ID) of second channel path port", type: "id" },


        CPCPPNAM: { description: "CPC - Partition name", type: "name" },
        CPCPUPID: { description: "CPC - User partition ID", type: "id" },
        CPCPOSNM: { description: "CPC - Operating system name", type: "name" },
        CPCPLPCN: { description: "CPC - LPAR cluster name", type: "name" },
        CPCPCGNM: { description: "CPC - Group capacity name", type: "name" },
        CPCPHGNM: { description: "CPC - Hardware group name to which this partition belongs", type: "name" },
        CPCPDMSU: { description: "CPC - Defined capacity limit", type: "nbr" },
        CPCPCAPD: { description: "CPC - Hardware capping options of this partition (Y=yes, N=no)", type: "status" },
        CPCPCAPI: { description: "CPC - Initial capping (yes/no/mix)", type: "status" },
        CPCPIND: { description: "CPC - Type/partition indicator", type: "type" },
        CPCPLCIW: { description: "CPC - Initial weight defined", type: "nbr" },
        CPCPLCMW: { description: "CPC - Minimum weight defined", type: "nbr" },
        CPCPLCXW: { description: "CPC - Maximum weight defined", type: "nbr" },
        CPCPCGLT: { description: "CPC - Group capacity limit", type: "nbr" },
        CPCPCGEM: { description: "CPC - Group minimum entitlement", type: "nbr" },
        CPCPCGEX: { description: "CPC - Group maximum entitlement", type: "nbr" },
        CPCPHWGC: { description: "CPC - Absolute hardware group capping limit for members of the same hardware group in numbers of CPUs", type: "nbr" },
        CPCPAMSU: { description: "CPC - Actual consumed MSUs", type: "nbr" },
        CPCPHWCC: { description: "CPC - Absolute physical hardware capacity limit in numbers of CPUs", type: "nbr" },
        CPCPLPNO: { description: "CPC - Average number of logical processors or cores", type: "nbr" },
        CPCPLEFU: { description: "CPC - Logical processor effective utilization %", type: "nbr" },
        CPCPLTOU: { description: "CPC - Logical processor total utilization %", type: "nbr" },
        CPCPPLMU: { description: "CPC - Physical LPAR utilization %", type: "nbr" },
        CPCPPEFU: { description: "CPC - Physical processor effective utilization %", type: "nbr" },
        CPCPPTOU: { description: "CPC - Physical processor total utilization %", type: "nbr" },
        CPCPLPND: { description: "CPC - Number of logical processors or cores defined", type: "nbr" },
        CPCPWGHT: { description: "CPC - Current weighting of shared CPU resources", type: "nbr" },
        CPCPDEDP: { description: "CPC - Number of dedicated processors online", type: "nbr" },
        CPCPLPSH: { description: "CPC - Percentage of the physical processor that a logical processor of the LPAR is entitled to use. If HiperDispatch is active, this is the percentage of logical processors with medium share.", type: "nbr" },
        CPCPVCMH: { description: "CPC - If HiperDispatch is active, this is the number of logical processors or cores with high share.", type: "nbr" },
        CPCPVCMM: { description: "CPC - If HiperDispatch is active, this is the number of logical processors or cores with medium share.", type: "nbr" },
        CPCPVCML: { description: "CPC - If HiperDispatch is active, this is the number of logical processors or cores with low share.", type: "nbr" },
        CPCPCSMB: { description: "CPC - Central storage in MB", type: "nbr" },
        CPCPBIIP: { description: "CPC - zIIP capacity boost active at end of MINTIME", type: "nbr" },
        CPCPBSPD: { description: "CPC - Speed boost active at end of MINTIME", type: "nbr" },


        JDELDAN: { description: "DELAY - Jobname or summary", type: "name" },
        JDELASI: { description: "DELAY - ASID", type: "id" },
        JDETYPE: { description: "DELAY - Class (A, B, E, O, S, or T)", type: "name" },
        JDETYPX: { description: "DELAY - Class (A, B, E, O, S, or T) with possible extension O", type: "name" },
        JDELDMN: { description: "DELAY - Domain number; no longer used", type: "nbr" },
        JDELPGN: { description: "DELAY - Performance group number; no longer used", type: "nbr" },
        JDEPSVCL: { description: "DELAY - Service class name", type: "name" },
        JDEGMIP: { description: "DELAY - Ind.Storage Critical and/or CPU Critical (S, C, or SC)", type: "type" },
        JDELWFL: { description: "DELAY - Work flow %", type: "nbr" },
        JDELUSG: { description: "DELAY - Using %", type: "nbr" },
        JDELDEL: { description: "DELAY - Delay %", type: "nbr" },
        JDELIDL: { description: "DELAY - Idle %", type: "nbr" },
        JDELUKN: { description: "DELAY - Unknown %", type: "nbr" },
        JDELPROC: { description: "DELAY - Processor delay %", type: "nbr" },
        JDELDEV: { description: "DELAY - Device delay %", type: "nbr" },
        JDELSTOR: { description: "DELAY - Storage delay %", type: "nbr" },
        JDELSUBS: { description: "DELAY - JES, HSM, and XCF delay %", type: "nbr" },
        JDELOPER: { description: "DELAY - Operator delay %", type: "nbr" },
        JDELENQ: { description: "DELAY - ENQ delay %", type: "nbr" },
        JDELJES: { description: "DELAY - JES delay %", type: "nbr" },
        JDELHSM: { description: "DELAY - HSM delay %", type: "nbr" },
        JDELXCF: { description: "DELAY - XCF delay %", type: "nbr" },
        JDELMNT: { description: "DELAY - Operator mount delay %", type: "nbr" },
        JDELMES: { description: "DELAY - Operator message delay %", type: "nbr" },
        JDELQUI: { description: "DELAY - Operator quiesce delay %", type: "nbr" },
        JDELREAS: { description: "DELAY - Primary reason", type: "name" },
        JDELCAP: { description: "DELAY - CAP delay %", type: "nbr" },
        JDELCP: { description: "DELAY - CP delay %", type: "nbr" },
        JDELCBP: { description: "DELAY - CBP delay %", type: "nbr" },
        JDELSUP: { description: "DELAY - zIIP delay %", type: "nbr" },
        JDELIFA: { description: "DELAY - zAAP delay %", type: "nbr" },


        DEVPJOB: { description: "DEV - Jobname", type: "name" },
        DEVPASI: { description: "DEV - ASID", type: "id" },
        DEVPCLA: { description: "DEV - Class (A, B, O, S, or T)", type: "name" },
        DEVPDMN: { description: "DEV - Domain number; no longer used", type: "nbr" },
        DEVPPGN: { description: "DEV - Performance group number; no longer used", type: "nbr" },
        DEVPSVCL: { description: "DEV - Service class name", type: "name" },
        DEVPODEL: { description: "DEV - Overall delay %", type: "nbr" },
        DEVPOUSE: { description: "DEV - Overall using %", type: "nbr" },
        DEVPCON: { description: "DEV - Connect time", type: "nbr" },
        DEV1SDEL: { description: "DEV - Delay % causes by volser1", type: "nbr" },
        DEV1VOLU: { description: "DEV - Volume serial number volser1", type: "nbr" },
        DEV2SDEL: { description: "DEV - Delay % caused by volser2", type: "nbr" },
        DEV2VOLU: { description: "DEV - Volume serial number volser2", type: "nbr" },
        DEV3SDEL: { description: "DEV - Delay % cause by volser3", type: "nbr" },
        DEV3VOLU: { description: "DEV - Volume serial number volser3", type: "nbr" },
        DEV4SDEL: { description: "DEV - Delay % cause by volser4", type: "nbr" },
        DEV4VOLU: { description: "DEV - Volume serial number volser4", type: "nbr" },


        DVRPVOLU: { description: "DEVR - Volser", type: "name" },
        DVRPDEVN: { description: "DEVR - 4-digit device number", type: "nbr" },
        DVRPDVN5: { description: "DEVR - 5-digit device number", type: "nbr" },
        DVRPIDEN: { description: "DEVR - Device indication (model)", type: "name" },
        DVRPSTAT: { description: "DEVR - Status", type: "status" },
        DVRPEXP: { description: "DEVR - Number of exposures", type: "nbr" },
        DVRPACTV: { description: "DEVR - % of active time", type: "nbr" },
        DVRPCONN: { description: "DEVR - % of connect time", type: "nbr" },
        DVRPDISC: { description: "DEVR - % of disconnect time", type: "nbr" },
        DVRPPEND: { description: "DEVR - % of pending time", type: "nbr" },
        DVRPDLYR: { description: "DEVR - Pending delay reason header", type: "name" },
        DVRPDLYP: { description: "DEVR - Pending delay reason %", type: "nbr" },
        DVRACTRT: { description: "DEVR - Device activity rate", type: "nbr" },
        DVRRESPT: { description: "DEVR - Response Time", type: "nbr" },
        DVRIOSQT: { description: "DEVR - IOS queue time", type: "nbr" },
        DVRPDVBT: { description: "DEVR - % of device busy delay time", type: "nbr" },
        DVRPCMRT: { description: "DEVR - % of control mode response time", type: "nbr" },
        DVRPCUBT: { description: "DEVR - % of control unit busy delay time", type: "nbr" },
        DVRPSPBT: { description: "DEVR - % of director port busy delay time", type: "nbr" },
        DVRRPTHP: { description: "DEVR - % of read pending time", type: "nbr" },
        DVRIQTHP: { description: "DEVR - % of I/O queue time high priority", type: "nbr" },
        DVRIOINT: { description: "DEVR - I/O intensity", type: "nbr" },
        DVRPJOBN: { description: "DEVR - Jobname", type: "name" },
        DVRPASI: { description: "DEVR - ASID", type: "id" },
        DVRPCLA: { description: "DEVR - Class (A, B, O, S, or T)", type: "name" },
        DVRPDMN: { description: "DEVR - Domain number; no longer used", type: "nbr" },
        DVRPPGN: { description: "DEVR - Performance group number; no longer used", type: "nbr" },
        DVRPSUSE: { description: "DEVR - % of using", type: "nbr" },
        DVRPSDEL: { description: "DEVR - % of delay", type: "nbr" },
        DVRPSVCL: { description: "DEVR - Service class", type: "name" },
        DVRPKIND: { description: "DEVR - Device type indicator", type: "type" },
        DVRPLCUN: { description: "DEVR - Logical control unit ID", type: "id" },


        DNDPDSN: { description: "DSND - Data set name", type: "name" },
        DNDPVOLU: { description: "DSND - Volume serial", type: "name" },
        DNDPJOBN: { description: "DSND - Jobname", type: "name" },
        DNDPASID: { description: "DSND - ASID", type: "id" },
        DNDPDUSG: { description: "DSND - DUSG (Using %)", type: "nbr" },
        DNDPDDLY: { description: "DSND - DDLY (Delay %)", type: "nbr" },


        SCMRPID: { description: "EADM - Card id", type: "id" },
        SCMUTL: { description: "EADM - LPAR utilization %", type: "nbr" },
        SCMUTLC: { description: "EADM - Tot. utilization %", type: "nbr" },
        SCMDRD: { description: "EADM - LPAR bytes read /sec.", type: "nbr" },
        SCMDRDC: { description: "EADM - Tot. bytes read /sec.", type: "nbr" },
        SCMDWR: { description: "EADM - LPAR bytes written /sec.", type: "nbr" },
        SCMDWRC: { description: "EADM - Tot. bytes written /sec.", type: "nbr" },
        SCMRQR: { description: "EADM - LPAR requests received /sec.", type: "nbr" },
        SCMRQRC: { description: "EADM - Tot. requests received /sec.", type: "nbr" },
        SCMART: { description: "EADM - LPAR resp.tme per request [msecs.]", type: "nbr" },
        SCMARTC: { description: "EADM - Tot. resp.tme per request [msecs.]", type: "nbr" },
        SCMAQTC: { description: "EADM - Tot. IOP queue time per request [msecs.]", type: "nbr" },
        SCMTRQ: { description: "EADM - LPAR number of requests", type: "nbr" },
        SCMTRQC: { description: "EADM - Tot. number of requests", type: "nbr" },

        SCMQR: { description: "EADM - LPAR requests processed /sec.", type: "nbr" },
        SCMQRC: { description: "EADM - Tot. requests processed /sec.", type: "nbr" },
        SCMTRQ: { description: "EADM - LPAR number of requests", type: "nbr" },
        SCMTRQC: { description: "EADM - Tot. number of requests", type: "nbr" },
        SCMHSCR: { description: "EADM - Number of SSCH instructions to all EADM devices /sec.", type: "nbr" },
        SCMHSCH: { description: "EADM - Tot. number of SSCH instructions to all EADM devices", type: "nbr" },
        SCMHFPT: { description: "EADM - Function pending time across all EADM devices [msecs.]", type: "nbr" },
        SCMHIQT: { description: "EADM - IOP queue time across all EADM devices [msecs.]", type: "nbr" },
        SCMHCRT: { description: "EADM - Command resp.tme across all EADM devices [msecs.]", type: "nbr" },


        ENCENAME: { description: "ENCLAVE - Name (generated)", type: "nbr" },
        ENCCLASS: { description: "ENCLAVE - Service class", type: "name" },
        ENCPER: { description: "ENCLAVE - Period", type: "nbr" },
        ENCDENC: { description: "ENCLAVE - Dependent enclave indicator", type: "type" },
        ENCXENC: { description: "ENCLAVE - Multi-system enclave indicator", type: "type" },
        ENCESTYP: { description: "ENCLAVE - Subsystem type", type: "type" },
        ENCEOWNM: { description: "ENCLAVE - Owner name", type: "name" },
        ENCEOSYS: { description: "ENCLAVE - Owner system", type: "name" },
        ENCETOKN: { description: "ENCLAVE - Export token", type: "name" },
        ENCTCPU: { description: "ENCLAVE - Tot CPU time (secs)", type: "nbr" },
        ENCXTOKN: { description: "ENCLAVE - Export token", type: "name" },
        ENCATT00: { description: "ENCLAVE - Selected attributes", type: "name" },
        ENCATT01: { description: "ENCLAVE - Accounting Information", type: "name" },
        ENCATT02: { description: "ENCLAVE - Collection Name", type: "name" },
        ENCATT03: { description: "ENCLAVE - Connection Type", type: "type" },
        ENCATT04: { description: "ENCLAVE - Correlation Information", type: "name" },
        ENCATT05: { description: "ENCLAVE - LU Name", type: "name" },
        ENCATT06: { description: "ENCLAVE - Net ID", type: "id" },
        ENCATT07: { description: "ENCLAVE - Package Name", type: " name" },
        ENCATT08: { description: "ENCLAVE - Plan Name", type: "name" },
        ENCATT09: { description: "ENCLAVE - Procedure Name", type: "name" },
        ENCATT10: { description: "ENCLAVE - Process Name", type: "name" },
        ENCATT11: { description: "ENCLAVE - Scheduling Environment", type: "name" },
        ENCATT12: { description: "ENCLAVE - Subsystem Collection Name", type: "name" },
        ENCATT13: { description: "ENCLAVE - Subsystem Instance", type: "name" },
        ENCATT14: { description: "ENCLAVE - Subsystem Parameter", type: "name" },
        ENCATT15: { description: "ENCLAVE - Subsystem Type", type: "type" },
        ENCATT16: { description: "ENCLAVE - Transaction/Job Class", type: "name" },
        ENCATT17: { description: "ENCLAVE - Transaction/Job Name", type: "name" },
        ENCATT18: { description: "ENCLAVE - User ID", type: "id" },
        ENCATT19: { description: "ENCLAVE - Priority", type: "status" },
        ENCATT20: { description: "ENCLAVE - Client IP Address", type: "name" },
        ENCATT21: { description: "ENCLAVE - Client User ID", type: "id" },
        ENCATT22: { description: "ENCLAVE - Client Transaction Name", type: "name" },
        ENCATT23: { description: "ENCLAVE - Client Workstation/Host name", type: "name" },
        ENCATT24: { description: "ENCLAVE - Client Accounting Information", type: "name" },
        ENCGOAL: { description: "ENCLAVE - Goal time", type: "nbr" },
        ENCGPERC: { description: "ENCLAVE - Goal percent", type: "nbr" },
        ENCTIFA: { description: "ENCLAVE - Tot zAAP time (secs)", type: "nbr" },
        ENCTIFC: { description: "ENCLAVE - Tot zAAP on CP time (secs)", type: "nbr" },
        ENCTCBP: { description: "ENCLAVE - Tot CBP time (secs)", type: "nbr" },
        ENCTCBC: { description: "ENCLAVE - Tot CBP on CP time (secs)", type: "nbr" },
        ENCDCPU: { description: "ENCLAVE - Delta CPU time (secs)", type: "nbr" },
        ENCDIFA: { description: "ENCLAVE - Delta zAAP time (secs)", type: "nbr" },
        ENCDIFC: { description: "ENCLAVE - Delta zAAP on CP time (secs)", type: "nbr" },
        ENCDCBP: { description: "ENCLAVE - Delta CBP time (secs)", type: "nbr" },
        ENCDCBC: { description: "ENCLAVE - Delta CBP on CP time (secs)", type: "nbr" },
        ENCDCPUP: { description: "ENCLAVE - Delta CPU % in Monitor III range", type: "nbr" },
        ENCDIFAP: { description: "ENCLAVE - Delta zAAP %", type: "nbr" },
        ENCDIFCP: { description: "ENCLAVE - Delta zAAP on CP %", type: "nbr" },
        ENCDCBPP: { description: "ENCLAVE - Delta CBP %", type: "nbr" },
        ENCDCBCP: { description: "ENCLAVE - Delta CBP on CP %", type: "nbr" },
        ENCSAMP: { description: "ENCLAVE - Tot execution samples", type: "nbr" },
        ENCTUSG: { description: "ENCLAVE - % Tot using samples", type: "nbr" },
        ENCTDLY: { description: "ENCLAVE - % Tot delay samples", type: "nbr" },
        ENCIDLE: { description: "ENCLAVE - % Idle", type: "nbr" },
        ENCCUSG: { description: "ENCLAVE - % CPU using", type: "nbr" },
        ENCIFAU: { description: "ENCLAVE - % zAAP using", type: "nbr" },
        ENCIFCU: { description: "ENCLAVE - % zAAP on CP using", type: "nbr" },
        ENCCBPU: { description: "ENCLAVE - % CBP using", type: "nbr" },
        ENCCBCU: { description: "ENCLAVE - % CBP on CP using", type: "nbr" },
        ENCCDLY: { description: "ENCLAVE - % CPU delay", type: "nbr" },
        ENCIUSG: { description: "ENCLAVE - % I/O using", type: "nbr" },
        ENCIDLY: { description: "ENCLAVE - % I/O delay", type: "nbr" },
        ENCIFAD: { description: "ENCLAVE - % zAAP delay", type: "nbr" },
        ENCCBPD: { description: "ENCLAVE - % CBP delay", type: "nbr" },
        ENCCCAP: { description: "ENCLAVE - % CPU capping", type: "nbr" },
        ENCSTOR: { description: "ENCLAVE - % Storage delay", type: "nbr" },
        ENCUNKN: { description: "ENCLAVE - % Unknown", type: "nbr" },
        ENCQUED: { description: "ENCLAVE - % Queue delay", type: "nbr" },
        ENCATTN: { description: "ENCLAVE - Number of attributes in table", type: "nbr" },
        ENCTSUP: { description: "ENCLAVE - Tot ZIIP time (secs)", type: "nbr" },
        ENCTSUC: { description: "ENCLAVE - Tot ZIIP on CP time (secs)", type: "nbr" },
        ENCDSUP: { description: "ENCLAVE - Delta ZIIP time (secs)", type: "nbr" },
        ENCDSUC: { description: "ENCLAVE - Delta ZIIP on CP time (secs)", type: "nbr" },
        ENCDSUPP: { description: "ENCLAVE - Delta ZIIP %", type: "nbr" },
        ENCDSUCP: { description: "ENCLAVE - Delta ZIIP on CP %", type: "nbr" },
        ENCSUPU: { description: "ENCLAVE - % ZIIP using", type: "nbr" },
        ENCSUCU: { description: "ENCLAVE - % ZIIP on CP using", type: "nbr" },
        ENCSUPD: { description: "ENCLAVE - % ZIIP delay", type: "nbr" },


        ENQPWJOB: { description: "ENQ - Jobname of waiting job", type: "name" },
        ENQPODEL: { description: "ENQ - Overall delay %", type: "nbr" },
        ENQPRDEL: { description: "ENQ - % of delay for the resource", type: "nbr" },
        ENQPWSTT: { description: "ENQ - Status of waiting job", type: "status" },
        ENQPMAJS: { description: "ENQ - Resource maj.name and scope or min.name", type: "name" },
        ENQPHDEL: { description: "ENQ - Holding % for the holding job", type: "nbr" },
        ENQPHJOB: { description: "ENQ - Jobname of holding job or system name for holding job", type: "name" },
        ENQPHSTT: { description: "ENQ - Status for the holding job", type: "status" },


        HJSPJOB: { description: "HSM - Jobname", type: "name" },
        HJSPODEL: { description: "HSM - Overall delay percentage", type: "nbr" },
        HJS1FDEL: { description: "HSM - Delay percentage", type: "nbr" },
        HJS1FCNR: { description: "HSM - Function code", type: "type" },
        HJS1EXPL: { description: "HSM - Explanation", type: "name" },
        HJS2FDEL: { description: "HSM - Delay percentage", type: "nbr" },
        HJS2FCNR: { description: "HSM - Function code", type: "type" },
        HJS2EXPL: { description: "HSM - Explanation", type: "name" },


        OPDPJOBN: { description: "OPD - Jobname", type: "name" },
        OPDPUSEN: { description: "OPD - User name", type: "name" },
        OPDPASID: { description: "OPD - ASID", type: "id" },
        OPDPASIX: { description: "OPD - Hexadecimal ASID", type: "id" },
        OPDPPRID: { description: "OPD - Process ID", type: "id" },
        OPDPPPID: { description: "OPD - Parent's process ID", type: "id" },
        OPDPLATW: { description: "OPD - Waiting for process latch", type: "status" },
        OPDPSTAT: { description: "OPD - Process state", type: "status" },
        OPDPAPPL: { description: "OPD - Percentage of TCB and SRB time", type: "nbr" },
        OPDPTOT: { description: "OPD - Total computing time since process has been started", type: "nbr" },
        OPDPSERV: { description: "OPD - Server type", type: "type" },
        OPDIPRID: { description: "OPD - Process ID", type: "id" },
        OPDIPPID: { description: "OPD - Parent's process ID", type: "id" },
        OPDIJOBN: { description: "OPD - Jobname", type: "name" },
        OPDIUSEN: { description: "OPD - User name", type: "name" },
        OPDIASID: { description: "OPD - ASID", type: "id" },
        OPDIASIX: { description: "OPD - Hexadecimal ASID", type: "id" },
        OPDITIMD: { description: "OPD - Start time/date", type: "status" },
        OPDIAPPL: { description: "OPD - Percentage of TCB and SRB time", type: "nbr" },
        OPDITOT: { description: "OPD - Total computing time since process has been started", type: "nbr" },
        OPDILPID: { description: "OPD - Latch process ID the process is waiting for (0 = not waiting)", type: "id" },
        OPDICMD: { description: "OPD - Command buffer", type: "status" },
        OPDISERN: { description: "OPD - Server name", type: "name" },
        OPDISERV: { description: "OPD - Server type", type: "type" },
        OPDIACTF: { description: "OPD - Number of active files", type: "nbr" },
        OPDIMAXF: { description: "OPD - Maximum files", type: "nbr" },
        OPDISTAT: { description: "OPD - Process state", type: "status" },
        OPDISTA1: { description: "OPD - 1. Possible state", type: "status" },
        OPDISTA2: { description: "OPD - 2. Possible state", type: "status" },
        OPDISTA3: { description: "OPD - 3. Possible state", type: "status" },
        OPDISTA4: { description: "OPD - 4. Possible state", type: "status" },
        OPDISTA5: { description: "OPD - 5. Possible state", type: "status" },


        PRCPJOB: { description: "PROC - Jobname", type: "name" },
        PRCPASI: { description: "PROC - AS ID (decimal)", type: "id" },
        PRCPCLA: { description: "PROC - Class (A, B, E, O, S, or T)", type: "name" },
        PRCPCLAX: { description: "PROC - Class (A, B, E, O, S, or T) with possible extension O", type: "name" },
        PRCPDMN: { description: "PROC - Domain number; no longer used", type: "nbr" },
        PRCPPGN: { description: "PROC - Performance group number; no longer used", type: "nbr" },
        PRCPSVCL: { description: "PROC - Service class name", type: "name" },
        PRCPODEL: { description: "PROC - Overall delay % for this AS", type: "nbr" },
        PRCPOUSE: { description: "PROC - Overall using % for this AS", type: "nbr" },
        PRCPTYPE: { description: "PROC - Proc type", type: "type" },
        PRCPTST: { description: "PROC - Overall app % for this AS", type: "nbr" },
        PRCPCAP: { description: "PROC - Capping delay %", type: "nbr" },
        PRCPETST: { description: "PROC - Overall app % including EAppl %", type: "nbr" },
        PRCPAPPL: { description: "PROC - Overall app % on behalf of this AS and proc type", type: "nbr" },
        PRCPEAPP: { description: "PROC - Overall app % including EAppl % on behalf of this AS and proc type", type: "nbr" },
        PRCPTWFL: { description: "PROC - Overall workflow % of this AS and proc type", type: "nbr" },
        PRCPTDEL: { description: "PROC - Overall delay % for this AS and proc type", type: "nbr" },
        PRCPTUSE: { description: "PROC - Overall using % for this AS and proc type", type: "nbr" },
        PRCPAACP: { description: "PROC - % zAAP on CP using", type: "nbr" },
        PRCPCBCP: { description: "PROC - % CBP on CP using", type: "nbr" },
        PRCPIICP: { description: "PROC - % ZIIP on CP using", type: "nbr" },
        PRC1SDEL: { description: "PROC - Delay % caused by jobname1", type: "nbr" },
        PRC1JOBN: { description: "PROC - Jobname1", type: "name" },
        PRC2SDEL: { description: "PROC - Delay % caused by jobname2", type: "nbr" },
        PRC2JOBN: { description: "PROC - Jobname2", type: "name" },
        PRC3SDEL: { description: "PROC - Delay % caused by jobname3", type: "nbr" },
        PRC3JOBN: { description: "PROC - Jobname3", type: "name" },
        PRCTCPUT: { description: "PROC - Total CPU time (milliseconds)", type: "nbr" },


        PRUPJOB: { description: "PROCU - Jobname", type: "name" },
        PRUPASI: { description: "PROCU - AS ID (decimal)", type: "id" },
        PRUPCLA: { description: "PROCU - Class (A, B, E, O, S, or T)", type: "name" },
        PRUPCLAX: { description: "PROCU - Class (A, B, E, O, S, or T) with possible extension O", type: "name" },
        PRUPSVCL: { description: "PROCU - Service class name", type: "name" },
        PRUPCLP: { description: "PROCU - Service class period", type: "name" },
        PRUPCPT: { description: "PROCU - Time on CP %", type: "nbr" },
        PRUPAACT: { description: "PROCU - zAAP time on CP %", type: "nbr" },
        PRUPCBCT: { description: "PROCU - CBP time on CP %", type: "nbr" },
        PRUPIICT: { description: "PROCU - ZIIP time on CP %", type: "nbr" },
        PRUPCPE: { description: "PROCU - CP EAppl %", type: "nbr" },
        PRUPAAPE: { description: "PROCU - zAAP EAppl %", type: "nbr" },
        PRUPCBPE: { description: "PROCU - CBP EAppl %", type: "nbr" },
        PRUPIIPE: { description: "PROCU - ZIIP EAppl %", type: "nbr" },
        PRUPTOTC: { description: "PROCU - % of tot accum. CPU time-consumed on behalf of this AS", type: "nbr" },
        PRUPTOTE: { description: "PROCU - % of tot accum. CPU time-consumed within this AS", type: "nbr" },
        PRUPTCB: { description: "PROCU - % of TCB time consumed in this AS", type: "nbr" },
        PRUPSRB: { description: "PROCU - % of SRB time consumed in this AS by local or global SRBs", type: "nbr" },
        PRUPPCS: { description: "PROCU - % of preemptable or client SRB time consumed on behalf of this AS", type: "nbr" },
        PRUPEPS: { description: "PROCU - % of preemptable or client SRB and enclave CPU time consumed within this AS", type: "nbr" },
        PRUPRPB: { description: "PROCU - % of preemptable SRB time consumed in this AS", type: "nbr" },
        PRUTCPUT: { description: "PROCU - Tot CPU time (msecs)", type: "nbr" },
        PRUTCPT: { description: "PROCU - Tot CPU time (msecs) on CP", type: "nbr" },
        PRUTAACT: { description: "PROCU - Tot zAAP time (msecs) on CP", type: "nbr" },
        PRUTCBCT: { description: "PROCU - Tot CBP time (msecs) on CP", type: "nbr" },
        PRUTIICT: { description: "PROCU - Tot ZIIP time (msecs) on CP", type: "nbr" },
        PRUTCPE: { description: "PROCU - Tot CP EAppl time (msecs)", type: "nbr" },
        PRUTAAPE: { description: "PROCU - Tot zAAP EAppl time (msecs)", type: "nbr" },
        PRUTCBPE: { description: "PROCU - Tot CBP EAppl time (msecs)", type: "nbr" },
        PRUTIIPE: { description: "PROCU - Tot ZIIP EAppl time (msecs)", type: "nbr" },
        PRUTTOTC: { description: "PROCU - Tot accum. CPU time-consumed on behalf of this AS", type: "nbr" },
        PRUTTOTE: { description: "PROCU - Tot accum. CPU time-consumed within this AS", type: "nbr" },
        PRUTTCB: { description: "PROCU - TCB time consumed in this AS", type: "nbr" },
        PRUTSRB: { description: "PROCU - SRB time consumed in this AS by local or global SRBs", type: "nbr" },
        PRUTPCS: { description: "PROCU - Preemptable or client SRB time consumed on behalf of this AS", type: "nbr" },
        PRUTEPS: { description: "PROCU - Preemptable or client SRB and enclave CPU time consumed within this AS", type: "nbr" },


        STRPJOB: { description: "STOR - Jobname", type: "name" },
        STRPASI: { description: "STOR - ASID", type: "id" },
        STRPCLA: { description: "STOR - Class (A, B, O, S, or T)", type: "name" },
        STRPSVCL: { description: "STOR - Service class name", type: "name" },
        STRPODEL: { description: "STOR - Overall delay %", type: "nbr" },
        STR1SDEL: { description: "STOR - Delay % COMM", type: "nbr" },
        STR2SDEL: { description: "STOR - Delay % local", type: "nbr" },
        STR3SDEL: { description: "STOR - Delay % VIO", type: "nbr" },
        STR4SDEL: { description: "STOR - Delay % SWAP", type: "nbr" },
        STR5SDEL: { description: "STOR - Delay % OUTR", type: "nbr" },
        STR6SDEL: { description: "STOR - Cross memory delay %", type: "nbr" },
        STR7SDEL: { description: "STOR - Hiperspace delay %", type: "nbr" },
        STR8SDEL: { description: "STOR - Other delays % (including VIO, XMEM and HIPR)", type: "nbr" },
        STRPACTV: { description: "STOR - Average ACTV frames", type: "nbr" },
        STRPFIXD: { description: "STOR - Average fixed frames total", type: "nbr" },
        STRPIDLE: { description: "STOR - Average IDLE frames", type: "nbr" },
        STRPWSET: { description: "STOR - Average working set frames", type: "nbr" },
        STRPWSEX: { description: "STOR - Average ES working set frames", type: "nbr" },
        STRPDMN: { description: "STOR - Domain number; no longer used", type: "nbr" },
        STRPPGN: { description: "STOR - Performance group number; no longer used", type: "nbr" },


        CSXNAME: { description: "STORC - Jobname", type: "name" },
        CSXACT: { description: "STORC - Active column", type: "name" },
        CSXCLA: { description: "STORC - Class (A, B, O, S, or T)", type: "name" },
        CSXSCN: { description: "STORC - Service class name", type: "name" },
        CSXASID: { description: "STORC - Address space identifier", type: "id" },
        CSXJESID: { description: "STORC - JES identifier", type: "id" },
        CSXTDATE: { description: "STORC - Termination date", type: "status" },
        CSXTTIME: { description: "STORC - Termination time", type: "status" },
        CSXTIME: { description: "STORC - Elapsed time", type: "status" },
        CSXPCSA: { description: "STORC - Percentage of CSA and RUCSA", type: "nbr" },
        CSXPECS: { description: "STORC - Percentage of ECSA and ERUCSA", type: "nbr" },
        CSXPSQA: { description: "STORC - Percentage of SQA", type: "nbr" },
        CSXPESQ: { description: "STORC - Percentage of ESQA", type: "nbr" },
        CSXPRUC: { description: "STORC - Percentage of RUCSA", type: "nbr" },
        CSXPERU: { description: "STORC - Percentage of ERUCSA", type: "nbr" },
        CSXACSA: { description: "STORC - Amount of CSA and RUCSA", type: "nbr" },
        CSXAECS: { description: "STORC - Amount of ECSA and ERUCSA", type: "nbr" },
        CSXASQA: { description: "STORC - Amount of SQA", type: "nbr" },
        CSXAESQ: { description: "STORC - Amount of ESQA", type: "nbr" },
        CSXARUC: { description: "STORC - Amount of RUCSA", type: "nbr" },
        CSXAERU: { description: "STORC - Amount of ERUCSA", type: "nbr" },


        CSXNAME: { description: "STORCR - Jobname", type: "name" },
        CSXJESID: { description: "STORCR - JES identifier", type: "id" },
        CSXTDATE: { description: "STORCR - Termination date", type: "status" },
        CSXTTIME: { description: "STORCR - Termination time", type: "status" },
        CSXACSA: { description: "STORCR - Amount of CSA and RUCSA", type: "nbr" },
        CSXAECS: { description: "STORCR - Amount of ECSA and ERUCSA", type: "nbr" },
        CSXASQA: { description: "STORCR - Amount of SQA", type: "nbr" },
        CSXAESQ: { description: "STORCR - Amount of ESQA", type: "nbr" },
        CSXARUC: { description: "STORCR - Amount of RUCSA", type: "nbr" },
        CSXAERU: { description: "STORCR - Amount of ERUCSA", type: "nbr" },


        STFPJOB: { description: "STORF - Jobname", type: "name" },
        STFPCLA: { description: "STORF - Class (A, B, O, S, or T)", type: "status" },
        STFPDMN: { description: "STORF - Domain number; no longer used", type: "nbr" },
        STFPPGN: { description: "STORF - Performance group number; no longer used", type: "nbr" },
        STFPSVCL: { description: "STORF - Service class name", type: "name" },
        STFPTOTL: { description: "STORF - Frame occupancy Total", type: "nbr" },
        STFPACTV: { description: "STORF - Frame occupancy ACTV", type: "nbr" },
        STFPIDLE: { description: "STORF - Frame occupancy IDLE", type: "id" },
        STFPWSET: { description: "STORF - Active frames WSET", type: "nbr" },
        STFPFIXD: { description: "STORF - Active frames FIXED", type: "nbr" },
        STFPDIV: { description: "STORF - Active frames DIV", type: "nbr" },
        STFPAUXS: { description: "STORF - Auxiliary storage slots", type: "nbr" },
        STFPPGIN: { description: "STORF - Page-in Rate", type: "nbr" },
        STFPEXIN: { description: "STORF - Page-in rate from expanded stg", type: "nbr" },
        STFPSPPI: { description: "STORF - Shared pages page-in rate from auxiliary stg", type: "nbr" },
        STFPTOTS: { description: "STORF - Tot number of shared page views", type: "nbr" },
        STFPSVIN: { description: "STORF - Tot number of valid shared pages", type: "nbr" },
        STFPSPVL: { description: "STORF - Shared pages validation rate", type: "nbr" },
        STFPLMO: { description: "STORF - Number of fixed 1 MB memory objects allocated", type: "nbr" },
        STFPLPR: { description: "STORF - Number of 1 MB frames fixed in real storage", type: "nbr" },
        STFPFREM: { description: "STORF - Number of freemained frames", type: "nbr" },
        STFPGMO: { description: "STORF - Number of 2 GB memory objects allocated", type: "nbr" },
        STFPGPR: { description: "STORF - Number of 2 GB frames fixed in central stg", type: "nbr" },


        STMPJOB: { description: "STORM - Jobname", type: "name" },
        STMPASI: { description: "STORM - AS identifier", type: "id" },
        STMPCLA: { description: "STORM - Class (A, B, O, S, or T)", type: "name" },
        STMPSVCL: { description: "STORM - Service class name", type: "name" },
        STMPCLP: { description: "STORM - Service class period", type: "nbr" },
        STMPTMO: { description: "STORM - Average number of memory objects allocated (by this AS)", type: "nbr" },
        STMPCMO: { description: "STORM - Average number of High Virtual common memory objects allocated (by this AS)", type: "nbr" },
        STMPSMO: { description: "STORM - Average number of High Virtual shared memory objects allocated (by this AS)", type: "nbr" },
        STMPPMO: { description: "STORM - Average number of High Virtual private memory objects allocated (by this AS)", type: "nbr" },
        STMPLMO: { description: "STORM - Average number of fixed memory objects allocated with this AS as the owner that can be backed in 1 MB frames", type: "nbr" },
        STMPLSMO: { description: "STORM - Average number of shared memory objects allocated with this AS as the owner that can be backed in 1 MB frames", type: "nbr" },
        STMPLFF: { description: "STORM - Average number of 1 MB page-fixed frames that are used by pageable/DREF memory objects owned by this AS", type: "nbr" },
        STMPLPF: { description: "STORM - Average number of 1 MB frames that are used by pageable/DREF memory objects owned by this AS.", type: "nbr" },
        STMPLFR: { description: "STORM - Average number of fixed 1 MB pages backed in central storage owned by this AS", type: "nbr" },
        STMPVTB: { description: "STORM - Average amount of stg alloc'd from Hi.Virt mem in mem objects owned by this AS", type: "nbr" },
        STMPCMB: { description: "STORM - Average amount of High Virtual common storage allocated owned by this AS", type: "nbr" },
        STMPVSB: { description: "STORM - Average amount of storage allocated in shared memory objects owned by this AS", type: "nbr" },
        STMPPMB: { description: "STORM - Average amount of High Virtual private storage allocated owned by this AS", type: "nbr" },
        STMPHCB: { description: "STORM - High water mark for the amount of High Virtual common storage allocated (in bytes)", type: "nbr" },
        STMPHSB: { description: "STORM - High water mark for the amount of storage allocated in shared memory objects (in bytes)", type: "nbr" },
        STMPLMB: { description: "STORM - AS memory limit", type: "nbr" },
        STMPGMO: { description: "STORM - Average number of fixed memory objects allocated with this AS as the owner that are backed in 2 GB frames", type: "nbr" },
        STMPGFR: { description: "STORM - Average number of fixed 2 GB pages backed in central storage owned by this AS", type: "nbr" },

        /*
        SRRVOLVC: "Volume serial number",
        SRRDEVTY: "Device type",
        SRRCUTY: "Control unit type",
        SRREXPCT: "Number of exposures",
        SRRUSVC: "% of using",
        SRRA1VC: "% of active",
        SRRA2VC: "% of connect",
        SRRA3VC: "% of disconnect",
        SRRA4VC: "% of pending",
        SRRA5VC: "% of DLY-DB",
        SRRA6VC: "% of DLY-CUB",
        SRRA7VC: "% of DLY-SPB",
        SRRSPTVC: "Space type",
        SRRAUTOT: "Average active users: TOTAL",
        SRRAULOC: "Average active users: LOCAL",
        SRRAUSWP: "Average active users: SWAP",
        SRRAUCOM: "Average active users: COMM",
        SRRPDLYR: "Delay type header",
        SRRPDLYP: "Delay reason %",
        */

        SRSPDMPG: { description: "SYSINFO - WLM group name for graphic report", type: "name" },
        SRSPDMN: { description: "SYSINFO - Domain number; no longer used", type: "nbr" },
        SRSPPGN: { description: "SYSINFO - Performance group number; no longer used", type: "nbr" },
        SRSPGNAM: { description: "SYSINFO - Name of WLM group", type: "name" },
        SRSPGTYP: { description: "SYSINFO - Type of WLM group", type: "type" },
        SRSPTOTU: { description: "SYSINFO - Total number of users", type: "type" },
        SRSPACTU: { description: "SYSINFO - Number of active users", type: "type" },
        SRS1SDEL: { description: "SYSINFO - Average number dely'd.x ANY", type: "type" },
        SRS2SDEL: { description: "SYSINFO - Average number dely'd.x COMM", type: "type" },
        SRS3SDEL: { description: "SYSINFO - Average number dely'd.x LOCL", type: "type" },
        SRS4SDEL: { description: "SYSINFO - Average number dely'd.x VIO", type: "type" },
        SRS5SDEL: { description: "SYSINFO - Average number dely'd.x SWAP", type: "type" },
        SRS6SDEL: { description: "SYSINFO - Average number dely'd.x OUTR", type: "type" },
        SRS7SDEL: { description: "SYSINFO - Average number dely'd.x cross memory", type: "type" },
        SRS8SDEL: { description: "SYSINFO - Average number dely'd.x hiperspace", type: "type" },
        SRS9SDEL: { description: "SYSINFO - Average number dely'd.x other reasons(VIO, XMEM and HIPR)", type: "type" },
        SRSPACTV: { description: "SYSINFO - Average ACTV frames", type: "type" },
        SRSPFIXD: { description: "SYSINFO - Average FIXED frames", type: "type" },
        SRSPIDLE: { description: "SYSINFO - Average IDLE frames", type: "type" },
        SRSPPGIN: { description: "SYSINFO - Page-in rate", type: "type" },
        SRSRCTNT: { description: "SYSINFO - Report class is a tenant report class", type: "type" },


        SYSNAMVC: { description: "SYSINFO - WLM group name", type: "name" },
        SYSTYPVC: { description: "SYSINFO - Type of WLM group", type: "type" },
        SYSWFLVC: { description: "SYSINFO - Workflow %", type: "nbr" },
        SYSTUSVC: { description: "SYSINFO - Average number total users", type: "nbr" },
        SYSAUSVC: { description: "SYSINFO - Average number active users", type: "nbr" },
        SYSTRSVC: { description: "SYSINFO - Transactions / sec", type: "nbr" },
        SYSAFCVC: { description: "SYSINFO - Active frames %", type: "nbr" },
        SYSVECVC: { description: "SYSINFO - Vector utilization", type: "status" },
        SYSRSPM: { description: "SYSINFO - Average response time /tx in msecs", type: "nbr" },
        SYSAUPVC: { description: "SYSINFO - Average number using PROC", type: "nbr" },
        SYSAUDVC: { description: "SYSINFO - Average number using DEV", type: "nbr" },
        SYSADPVC: { description: "SYSINFO - Average number dly'd.x PROC", type: "nbr" },
        SYSADDVC: { description: "SYSINFO - Average number dly'd.x DEV", type: "nbr" },
        SYSADSVC: { description: "SYSINFO - Average number dly'd.x STOR", type: "nbr" },
        SYSADUVC: { description: "SYSINFO - Average number dly'd.x SUBS", type: "nbr" },
        SYSADOVC: { description: "SYSINFO - Average number dly'd.x OPER", type: "nbr" },
        SYSADEVC: { description: "SYSINFO - Average number dly'd.x ENQ", type: "nbr" },
        SYSADJVC: { description: "SYSINFO - Average number dly'd.x JES", type: "nbr" },
        SYSADHVC: { description: "SYSINFO - Average number dly'd.x HSM", type: "nbr" },
        SYSADXVC: { description: "SYSINFO - Average number dly'd.x XCF", type: "nbr" },
        SYSADNVC: { description: "SYSINFO - Average number dly'd.x Mount", type: "nbr" },
        SYSADMVC: { description: "SYSINFO - Average number dly'd.x Message", type: "nbr" },
        SYSCPUVC: { description: "SYSINFO - SYSCPUVC", type: "type" },
        SYSSRBVC: { description: "SYSINFO - SYSSRBVC", type: "type" },
        SYSTCBVC: { description: "SYSINFO - SYSTCBVC", type: "type" },
        SYSEAPVC: { description: "SYSINFO - SYSEAPVC", type: "type" },
        SYSIFAVC: { description: "SYSINFO - SYSIFAVC", type: "type" },
        SYSCPVC: { description: "SYSINFO - SYSCPVC", type: "type" },
        SYSIFCVC: { description: "SYSINFO - SYSIFCVC", type: "type" },
        SYSRSPVC: { description: "SYSINFO - Average response time /tx in secs", type: "nbr" },
        SYSVELVC: { description: "SYSINFO - Execution velocity", type: "nbr" },
        SYSUGMVC: { description: "SYSINFO - % using", type: "nbr" },
        SYSUGPVC: { description: "SYSINFO - % using processor", type: "nbr" },
        SYSUGDVC: { description: "SYSINFO - % using device", type: "nbr" },
        SYSWGDVC: { description: "SYSINFO - % device workflow", type: "nbr" },
        SYSWGPVC: { description: "SYSINFO - % processor workflow", type: "nbr" },
        SYSDGMVC: { description: "SYSINFO - % delay", type: "nbr" },
        SYSUJMVC: { description: "SYSINFO - Average number of users using", type: "nbr" },
        SYSDJMVC: { description: "SYSINFO - Average number of users delayed", type: "nbr" },
        SYSDGEVC: { description: "SYSINFO - % delay for ENQ", type: "nbr" },
        SYSDGHVC: { description: "SYSINFO - % delay for HSM", type: "nbr" },
        SYSDGDVC: { description: "SYSINFO - % delay for DEV", type: "nbr" },
        SYSDGJVC: { description: "SYSINFO - % delay for JES", type: "nbr" },
        SYSDGOVC: { description: "SYSINFO - % delay for OPER", type: "nbr" },
        SYSDGPVC: { description: "SYSINFO - % delay for PROC", type: "nbr" },
        SYSDGSVC: { description: "SYSINFO - % delay for STOR", type: "nbr" },
        SYSDGUVC: { description: "SYSINFO - % delay for SUBS", type: "nbr" },
        SYSDGXVC: { description: "SYSINFO - % delay for XCF", type: "nbr" },
        SYSDDSIN: { description: "SYSINFO - Delayed dispatching interval", type: "nbr" },
        SYSDDSIT: { description: "SYSINFO - Delayed dispatching interval total", type: "nbr" },
        SYSDDSIP: { description: "SYSINFO - Delayed dispatching interval peak", type: "nbr" },
        SYSLPIVC: { description: "SYSINFO - % of LPAR idle", type: "nbr" },
        SYSSUPVC: { description: "SYSINFO - SYSSUPVC", type: "type" },
        SYSSUCVC: { description: "SYSINFO - SYSSUCVC", type: "type" },
        SYSPDPVC: { description: "SYSINFO - SYSPDPVC", type: "type" },
        SYSTODVC: { description: "SYSINFO - % of total delay samples", type: "nbr" },
        SYSCPDVC: { description: "SYSINFO - % of CP delay samples", type: "nbr" },
        SYSAPDVC: { description: "SYSINFO - % of ZAAP delay samples", type: "nbr" },
        SYSIPDVC: { description: "SYSINFO - % of ZIIP delay samples", type: "nbr" },
        SYSRGCVC: { description: "SYSINFO - CPU cap because resource grp max being enforced", type: "nbr" },
        SYSDLYVC: { description: "SYSINFO - % of delay", type: "nbr" },
        SYSRCTNT: { description: "SYSINFO - Report class is a tenant report class", type: "name" },
        SYSMEMUS: { description: "SYSINFO - Memory used, actual", type: "nbr" },


        JUSPJOB: { description: "USAGE - Jobname", type: "name" },
        JUSPASI: { description: "USAGE - AS ID (decimal)", type: "id" },
        JUSPCLA: { description: "USAGE - Job class", type: "name" },
        JUSPCLAX: { description: "USAGE - Extended job class", type: "name" },
        JUSPSVCL: { description: "USAGE - Service class", type: "name" },
        JUSPCLP: { description: "USAGE - Service class period", type: "nbr" },
        JUSPDP: { description: "USAGE - Dispatching priority", type: "nbr" },
        JUSPTAT: { description: "USAGE - TX active time", type: "nbr" },
        JUSPTRT: { description: "USAGE - TX resident time", type: "id" },
        JUSPTCT: { description: "USAGE - TX count", type: "nbr" },
        JUSPFRT: { description: "USAGE - Frames total", type: "nbr" },
        JUSPFRXT: { description: "USAGE - Fixed frames total", type: "nbr" },
        JUSPFRXH: { description: "USAGE - Fixed frames high", type: "nbr" },
        JUSPFRXA: { description: "USAGE - Fixed frames between 16M and 2G", type: "nbr" },
        JUSPFRXB: { description: "USAGE - Fixed frames below 16M", type: "nbr" },
        JUSPDCTT: { description: "USAGE - Dev.conn.tme total since AS creation [secs]", type: "nbr" },
        JUSPDCTD: { description: "USAGE - Dev.conn.time for interval [secs]", type: "nbr" },
        JUSPEXCT: { description: "USAGE - Total number of EXCP ops since AS creation", type: "nbr" },
        JUSPEXCD: { description: "USAGE - Number of EXCP operations for interval", type: "nbr" },
        JUSPEXCR: { description: "USAGE - Number of EXCP operations per second", type: "nbr" },
        JUSPCPUT: { description: "USAGE - CPU time total since AS creation [secs]", type: "nbr" },
        JUSPCPUD: { description: "USAGE - CPU time for interval [secs]", type: "nbr" },
        JUSPTCBT: { description: "USAGE - TCB time tot since AS creation [secs]", type: "nbr" },
        JUSPTCBD: { description: "USAGE - TCB time for interval [secs]", type: "nbr" },
        JUSPQREQ: { description: "USAGE - GQSCAN requests", type: "nbr" },
        JUSPQSPR: { description: "USAGE - GQSCAN specific requests", type: "nbr" },
        JUSPQRES: { description: "USAGE - Average number of GQSCAN resources", type: "nbr" },
        JUSPQRSD: { description: "USAGE - GQSCAN resource count std.dev", type: "nbr" },
        JUSPQTIM: { description: "USAGE - Average GQSCAN req.tme", type: "nbr" },
        JUSPQTSD: { description: "USAGE - GQSCAN request time std.dev", type: "nbr" },
        JUSPRPB: { description: "USAGE - % of preemptable SRB time", type: "nbr" },

        /*
        CADPVOLU: "Volume",
        CADPDEVN: "Four-digit device number",
        CADPDVN5: "Five-digit device number",
        CADPSSID: "SSID",
        CADVCACH: "Cache state for volume",
        CADVDFW: "DFW state for volume",
        CADVPIN: "Pinned state for volume",
        CADVMMDB: "Delayed Operations due to NVS for volume",
        CADVMNCI: "Non-cache ICL for volume",
        CADVMCWR: "CKD write for volume",
        CADVMCRM: "Read miss for volume",
        CADVMMCB: "Delayed Operations due to Cache for volume",
        CADVMNCB: "Non-cache bypass for volume",
        CADVMCHI: "CKD hits for volume",
        CADVMCWP: "Write prom for volume",
        CADVMMDI: "DFW inhibit for volume",
        CADSNRRA: "Norm Read rate for SSID",
        CADSNRHI: "Norm Read hit rate for SSID",
        CADSNRHP: "Norm Read hit percentage for SSID",
        CADSNWRA: "Norm Write rate for SSID",
        CADSNWFA: "Norm Write fast rate for SSID",
        CADSNWHI: "Norm Write hit rate for SSID",
        CADSNWHP: "Norm Write hit percentage for SSID",
        CADSNREP: "Norm Read percentage for SSID",
        CADSNTRA: "Norm Tracks rate for SSID",
        CADSSRRA: "Seq Read rate for SSID",
        CADSSRHI: "Seq Read hit rate for SSID",
        CADSSRHP: "Seq Read hit percentage for SSID",
        CADSSWRA: "Seq Write rate for SSID",
        CADSSWFA: "Seq Write fast rate for SSID",
        CADSSWHI: "Seq Write hit rate for SSID",
        CADSSWHP: "Seq Write hit percentage for SSID",
        CADSSREP: "Seq Read percentage for SSID",
        CADSSTRA: "Seq Tracks rate for SSID",
        CADSCRRA: "CFW Read rate for SSID",
        CADSCRHI: "CFW Read hit rate for SSID",
        CADSCRHP: "CFW Read hit percentage for SSID",
        CADSCWRA: "CFW Write rate for SSID",
        CADSCWFA: "CFW Write fast rate for SSID",
        CADSCWHI: "CFW Write hit rate for SSID",
        CADSCWHP: "CFW Write hit percentage for SSID",
        CADSCREP: "CFW Read percentage for SSID",
        CADSTRRA: "Total Read rate for SSID",
        CADSTRHI: "Total Read hit rate for SSID",
        CADSTRHP: "Total Read hit percentage for SSID",
        CADSTWRA: "Total Write rate for SSID",
        CADSTWFA: "Total Write fast rate for SSID",
        CADSTWHI: "Total Write hit rate for SSID",
        CADSTWHP: "Total Write hit percentage for SSID",
        CADSTREP: "Total Read percentage for SSID",
        CADSMMDB: "Delayed Operations due to NVS for SSID",
        CADSMNCI: "Non-cache ICL for SSID",
        CADSMCWR: "CKD write for SSID",
        CADSMCRM: "Read miss for SSID",
        CADSMMCB: "Delayed Operations due to Cache for SSID",
        CADSMNCB: "Non-cache bypass for SSID",
        CADSMCHI: "CKD hits for SSID",
        CADSMCWP: "Write prom for SSID",
        CADSMMDI: "DFW inhibit for SSID",
        CADPIOP: "I/O percentage",
        CADPIO: "I/O rate",
        CADPHITP: "Hit percentage",
        CADPREAD: "Cache hit rate READ",
        CADPDFW: "Cache hit rate DFW",
        CADPCFW: "Cache hit rate CFW",
        CADPTOT: "DASD I/O rate total",
        CADPSTAG: "DASD I/O rate stage",
        CADPSEQ: "Sequential rate",
        CADPASYN: "Async rate",
        CADVNRRA: "Norm Read rate for volume",
        CADVNRHI: "Norm Read hit rate for volume",
        CADVNRHP: "Norm Read hit percentage for volume",
        CADVNWRA: "Norm Write rate for volume",
        CADVNWFA: "Norm Write fast rate for volume",
        CADVNWHI: "Norm Write hit rate for volume",
        CADVNWHP: "Norm Write hit percentage for volume",
        CADVNREP: "Norm Read percentage for volume",
        CADVNTRA: "Norm Tracks rate for volume",
        CADVSRRA: "Seq Read rate for volume",
        CADVSRHI: "Seq Read hit rate for volume",
        CADVSRHP: "Seq Read hit percentage for volume",
        CADVSWRA: "Seq Write rate for volume",
        CADVSWFA: "Seq Write fast rate for volume",
        CADVSWHI: "Seq Write hit rate for volume",
        CADVSWHP: "Seq Write hit percentage for volume",
        CADVSREP: "Seq Read percentage for volume",
        CADVSTRA: "Seq Tracks rate for volume",
        CADVCRRA: "CFW Read rate for volume",
        CADVCRHI: "CFW Read hit rate for volume",
        CADVCRHP: "CFW Read hit percentage for volume",
        CADVCWRA: "CFW Write rate for volume",
        CADVCWFA: "CFW Write fast rate for volume",
        CADVCWHI: "CFW Write hit rate for volume",
        CADVCWHP: "CFW Write hit percentage for volume",
        CADVCREP: "CFW Read percentage for volume",
        CADVTRRA: "Total Read rate for volume",
        CADVTRHI: "Total Read hit rate for volume",
        CADVTRHP: "Total Read hit percentage for volume",
        CADVTWRA: "Total Write rate for volume",
        CADVTWFA: "Total Write fast rate for volume",
        CADVTWHI: "Total Write hit rate for volume",
        CADVTWHP: "Total Write hit percentage for volume",
        CADVTREP: "Total Read percentage for volume",


        CASPSSID: "SSID",
        CASPCUID: "CUID",
        CASPTYPM: "Type-Mod",
        CASPSIZE: "Storage size",
        CASMCACH: "Cache state",
        CASMCCON: "Cache configured",
        CASMCAVL: "Cache available",
        CASMCOFF: "Cache offline",
        CASMCPIN: "Cache pinned",
        CASMNVS: "NVS state",
        CASMNCON: "NVS configured",
        CASPIO: "I/O rate",
        CASMNPIN: "NVS pinned",
        CASPHITP: "Hit percentage",
        CASPHIT: "Hit rate",
        CASPMTOT: "Miss total rate",
        CASPMSTG: "Miss stage rate",
        CASPREAP: "Read percentage",
        CASPSEQ: "Sequential rate",
        CASPASYN: "Async rate",
        CASPOFF: "Off rate",
        CASNRRA: "Norm Read rate",
        CASNRHI: "Norm Read hit rate",
        CASNRHIP: "Norm Read hit percentage",
        CASNWRA: "Norm Write rate",
        CASNWFA: "Norm Write fast rate",
        CASNWHI: "Norm Write hit rate",
        CASNWHIP: "Norm Write hit percentage",
        CASNREAP: "Norm Read percentage",
        CASNTRA: "Norm Tracks rate",
        CASSRRA: "Seq Read rate",
        CASSRHI: "Seq Read hit rate",
        CASSRHIP: "Seq Read hit percentage",
        CASSWRA: "Seq Write rate",
        CASSWFA: "Seq Write fast rate",
        CASSWHI: "Seq Write hit rate",
        CASSWHIP: "Seq Write hit percentage",
        CASSREAP: "Seq Read percentage",
        CASSTRA: "Seq Tracks rate",
        CASCRRA: "CFW Read rate",
        CASCRHI: "CFW Read hit rate",
        CASCRHIP: "CFW Read hit percentage",
        CASCWRA: "CFW Write rate",
        CASCWFA: "CFW Write fast rate",
        CASCWHI: "CFW Write hit rate",
        CASCWHIP: "CFW Write hit percentage",
        CASCREAP: "CFW Read percentage",
        CASTRRA: "Total Read rate",
        CASTRHI: "Total Read hit rate",
        CASTRHIP: "Total Read hit percentage",
        CASTWRA: "Total Write rate",
        CASTWFA: "Total Write fast rate",
        CASTWHI: "Total Write hit rate",
        CASTWHIP: "Total Write hit percentage",
        CASTREAP: "Total Read percentage",


        CFAPSTRU: "Structure name",
        CFAPTYPE: "Structure type",
        CFAPSTAT: "Structure status",
        CFAPSYS: "System name",
        CFAINAM: "Coupling facility name",
        CFAISTRU: "Structure name",
        CFAITYPE: "Structure type",
        CFAICNAM: "Connection name",
        CFAICJOB: "Job name",
        CFAICSTA: "Status",
        CFAICPRB: "Problem status",
        CFAICASI: "ASID",
        CFAICLVL: "CF level",
        CFAPSTEX: "Structure status extension",
        CFAISTRC: "Structure storage class",
        CFAPENCR: "Encryption indicator of CF structure",
        CFAICREB: "User managed rebuild allowed",
        CFAICDRB: "User managed rebuild with duplexing allowed",
        CFAICALT: "Altering allowed",
        CFAICAUT: "System managed processes allowed",
        CFAICSUS: "Suspension of work is tolerated",
        CFAIFCCL: "First castout class",
        CFAILCCL: "Last castout class",
        CFAIPREF: "Allocation preference list",
        CFAIEXCL: "Exclusion preference list",
        CFAISALG: "SCM Algorithm Type",
        CFAPSTEP: "Structure execution %",
        CFAPUTIP: "CPU utilization %",
        CFAPSYNR: "Sync rate",
        CFAPASS: "Sync average service time",
        CFAPSYNC: "Number of synchronous requests",
        CFAPASYR: "Async rate",
        CFAPAAS: "Async average service time",
        CFAPASYC: "Number of asynchronous requests",
        CFAPACHG: "Async changed %",
        CFAPADEL: "Async delay %",
        CFAPQRT: "Average queued request time",
        CFAPCNVC: "Converted request count",
        CFAPDELC: "Operation count delayed for dump serialization",
        CFAPQUEC: "Queued operation count",
        CFAPMUSR: "Maximum number of users",
        CFAPTUSR: "Total number of users",
        CFAPPUSR: "Number of problem users",
        CFAPREBP: "Rebuild percentage",
        CFAISTRS: "Structure size",
        CFAISTRP: "Structure size %",
        CFAISTUP: "Structure utilized storage %",
        CFAISTRM: "Min structure size",
        CFAISTRX: "Max structure size",
        CFAIDTS: "Dump table size",
        CFAILDES: "Data element size (LIST/LOCK only)",
        CFAILDLS: "Data list entry size (LIST/LOCK only)",
        CFAILEL: "List entries total (LIST/LOCK only)",
        CFAILEM: "List entries current (LIST/LOCK only)",
        CFAIMAE: "Data elements total (LIST only)",
        CFAICUE: "Data elements current (LIST only)",
        CFAILTL: "Lock entries total (LIST/LOCK only)",
        CFAILTM: "Lock entries current (LIST/LOCK only)",
        CFAIDES: "Data element size (CACHE only)",
        CFAIDEN: "Directory entries total (CACHE only)",
        CFAIDEC: "Directory entries current (CACHE only)",
        CFAICEN: "Directory entries changed (CACHE only)",
        CFAIDEL: "Data elements total (CACHE only)",
        CFAIDAC: "Data elements current (CACHE only)",
        CFAICEL: "Data elements changed (CACHE only)",
        CFAICONT: "Contention %",
        CFAIFCON: "False Contention % (LOCK only)",
        CFAIREQR: "Request rate (CACHE only)",
        CFAIREAR: "Read rate (CACHE only)",
        CFAIWRIR: "Write rate (CACHE only)",
        CFAICAOR: "Castout rate (CACHE only)",
        CFAIXIR: "XI rate (CACHE only)",
        CFAIDER: "Directory reclaims (CACHE only)",
        CFAISPCF: "% of CF storage",
        CFAISAUM: "Estimated Max. of Augmented Space (LIST only)",
        CFAISAUP: "% Augmented Space Used (LIST only)",
        CFAISSCM: "SCM Space Maximum (LIST only)",
        CFAISSCP: "SCM Space % Used (LIST only)",
        CFAISLTM: "SCM List Entries Est Max (LIST only)",
        CFAISLTC: "SCM List Entries Current (LIST only)",
        CFAISLMM: "SCM List Elements Est Max (LIST only)",
        CFAISLMC: "SCM List Elements Current (LIST only)",


        CFOPNAM: "Coupling facility name",
        CFOPMOD: "Model",
        CFOPVER: "Version",
        CFOPLVL: "CF level",
        CFOPDYND: "CF dynamic dispatching",
        CFOPSTAT: "Status of CF",
        CFOPVOL: "Volatility status",
        CFOPDEF: "Processor defined",
        CFOPMNT: "Maintenance mode active",
        CFOPRCV: "Recovery manager active",
        CFOPUTIP: "Processor utilization %",
        CFOPPDED: "Number of dedicated processors",
        CFOPPSHR: "Number of shared processors",
        CFOPPWGT: "Average weighting of shared processors",
        CFOPEFF: "Processor effective",
        CFOPREQR: "Request rate",
        CFOPTSD: "Storage size",
        CFOPTSF: "Storage available",
        CFOPUTIS: "Utilized storage %",
        CFOPTCS: "Total control space",
        CFOPFCS: "Free control space",
        CFOPDTS: "Dump table control space",
        CFOPDTUS: "Dump table in use",
        CFOPSYSC: "Connected MVS system count",
        CFOPSTCI: "Structure count in policy",
        CFOPSTCO: "Structure count out policy",
        CFOPSCMS: "Storage Class Memory size",
        CFOPSCMA: "Storage Class Memory available",
        CFOPSCMU: "Utilized Storage Class Memory %",
        CFOPAUGS: "Augmented space maximum",
        CFOPAUGA: "Augmented space available",
        CFOPAUGU: "% Utilized augmented space",
        CFOPSMSC: "Sum of maximum storage class memory",


        CFSPNAM: "Coupling facility name",
        CFSPSYS: "System name",
        CFSINAM: "Coupling facility name",
        CFSIPATH: "Paths IDs",
        CFSIPTYP: "TYPES variable string",
        CFSITYPE: "Path types",
        CFSICPIn: "Channel path ID (nth of eight)",
        CFSICPTn: "Channel path type (nth of eight)",
        CFSICPOn: "Channel path operation mode (nth of eight)",
        CFSICPDn: "Degraded Mode indicator for the channel path (nth of eight)",
        CFSICPLn: "Estimated distance in kilometers (nth of eight)",
        CFSIPHYn: "Physical channel path ID (nth of eight)",
        CFSIHCAn: "Host communication adapter ID (nth of eight)",
        CFSIHCPn: "Host communication adapter port number (nth of eight)",
        CFSIIOPn: "IOP ID (nth of eight)",
        CFSPSDEL: "Subchannel delay %",
        CFSPSBSP: "Subchannel busy %",
        CFSPPTHA: "Paths available",
        CFSPPDEL: "Paths delay %",
        CFSPSYNR: "Sync rate",
        CFSPASS: "Sync average service time",
        CFSPSYNC: "Synchronous request count",
        CFSPSOPD: "Average synchronous operation delay",
        CFSPSYNP: "Synchronous request %",
        CFSPASYR: "Async rate",
        CFSPAAS: "Async average service time",
        CFSPASYC: "Asynchronous request count",
        CFSPACHG: "Async changed %",
        CFSPADEL: "Async delay %",
        CFSPASYP: "Asynchronous request %",
        CFSPREQC: "Total request %",
        CFSPFOPT: "Average failed operation time",
        CFSPCNVC: "Synchronous to asynchronous conversion rate",
        CFSISCG: "Subchannels generated",
        CFSISCU: "Subchannels in use",
        CFSISCL: "Subchannels max",


        CRYCTYPE: "Type of cryptographic hardware function",
        CRYCIDX: "Index of cryptographic hardware function",
        CRYCPC: "CPC name",
        CRYSYS: "System name",
        CRYUDID: "Usage domain ID",
        CRYSCPM: "Scope of performance metrics (C, S)",
        CRYCMODE: "Cryptographic mode",
        CRYOPRT: "Rate of all operations",
        CRYOPET: "Average execution time (in milliseconds) of all operations",
        CRYTUTL: "Total utilization percentage",
        CRCKGORT: "Rate for RSA-key-generation operations (CCA coprocessor mode)",
        CRCKGOET: "Average execution time (in milliseconds) for RSA-key-generation operations (CCA coprocessor mode)",
        CRCKGUTL: "Utilization percentage for RSA-key-generation operations (CCA coprocessor mode)",
        CRARKLEN: "RSA key length (accelerator mode)",
        CRAMOPRT: "Rate of ME-format RSA operations (accelerator mode)",
        CRAMOPET: "Average execution time (in milliseconds) of ME-format RSA operations (accelerator mode)",
        CRAMUTL: "Utilization percentage of ME-format RSA operations (accelerator mode)",
        CRACOPRT: "Rate of CRT-format RSA operations (accelerator mode)",
        CRACOPET: "Average execution time (in milliseconds) of CRT-format RSA operations (accelerator mode)",
        CRACUTL: "Utilization percentage of CRT-format RSA operations (accelerator mode)",
        CRPSART: "Rate of slow asymmetric-key operations (PKCS11 coprocessor mode)",
        CRPSAET: "Average execution time (in milliseconds) of slow asymmetric-key operations (PKCS11 coprocessor mode)",
        CRPSAUTL: "Utilization percentage of slow asymmetric-key operations (PKCS11 coprocessor mode)",
        CRPFART: "Rate of fast asymmetric-key operations (PKCS11 coprocessor mode)",
        CRPFAET: "Average execution time (in milliseconds) of fast asymmetric-key operations (PKCS11 coprocessor mode)",
        CRPFAUTL: "Utilization percentage of fast asymmetric-key operations (PKCS11 coprocessor mode)",
        CRPSPRT: "Rate of symmetric-key operations that return partial or incremental results (PKCS11 coprocessor mode)",
        CRPSPET: "Average execution time (in milliseconds) of symmetric-key operations that return partial or incremental results (PKCS11 coprocessor mode)",
        CRSPUTL: "Utilization percentage of symmetric-key operations that return partial or incremental results (PKCS11 coprocessor mode)",
        CRPSCRT: "Rate of symmetric-key operations that return complete or final results (PKCS11 coprocessor mode)",
        CRPSCET: "Average execution time (in milliseconds) of symmetric-key operations that return complete or final results (PKCS11 coprocessor mode)",
        CRPSCUTL: "Utilization percentage of symmetric-key operations that return complete or final results (PKCS11 coprocessor mode)",
        CRPAGRT: "Rate of asymmetric-key generation operations (PKCS11 coprocessor mode)",
        CRPAGET: "Average execution time (in milliseconds) of asymmetric-key generation operations (PKCS11 coprocessor mode)",
        CRPAGUTL: "Utilization percentage of asymmetric-key generation operations (PKCS11 coprocessor mode)",
        CRYSID: "SMF system ID",


        JDJLDAN: "Jobname or summary",
        JDJLASID: "Address space identification",
        JDJCLASS: "Class (A, B, E, O, S, or T)",
        JDJCLASX: "Class (A, B, E, O, S, or T) with possible extension O",
        JDJLDMN: "Domain number; no longer used",
        JDJLPGN: "Performance group number; no longer used",
        JDJPSVCL: "Service class name",
        JDJLWFL: "Work flow %",
        JDJLUSP: "Processor using %",
        JDJLUSD: "Device using %",
        JDJLUSG: "Using %",
        JDJLDEL: "Delay %",
        JDJLIDL: "Idle %",
        JDJLUKN: "Unknown %",
        JDJLPROC: "Processor delay %",
        JDJLDEV: "Device delay %",
        JDJLSTOR: "Storage delay %",
        JDJLSUBS: "SUBS delay %",
        JDJLOPER: "Operator delay %",
        JDJLENQ: "ENQ delay %",
        JDJLJES: "JES delay %",
        JDJLHSM: "HSM delay %",
        JDJLXCF: "XCF delay %",
        JDJLMNT: "Operator mount delay %",
        JDJLMES: "Operator message delay %",
        JDJLQUI: "Operator quiesce delay %",
        JDJLREAS: "Primary reason",


        SPDPVOL: "Volume",
        SPDPSGN: "Storage group name",
        SPDPTSP: "Total capacity in MB",
        SPDPFSP: "Free space in MB",
        SPDPFSR: "Free space percentage",
        SPDPLBK: "Largest block in MB",


        SPGPSGN: "Storage Group",
        SPGPTSP: "Total capacity in MB",
        SPGPFSP: "Free space in MB",
        SPGPFSR: "Free space percentage",
        SPGPNVO: "Number of Volumes",


        SRGNAME: "Name of resource group or tenant resource group",
        SRGTYPE: "Resource group type",
        SRGDESCD: "Resource group description",
        SRGSYS: "System name",
        SRGSID: "SMF ID",
        SRGSCTRC: "Associated service class or tenant report class",
        SRGSRTYP: "Definition of min and max capacity",
        SRGSPINC: "Include specialty processor consumption",
        SRGSRMIN: "Srv.rate(cap), min",
        SRGSRMAX: "Srv.rate(cap), max",
        SRGSRACP: "Srv.rate(cap), actual in nbr of CPs",
        SRGSRAMS: "Srv.rate(cap), actual in MSU",
        SRGSRASU: "Srv.rate(cap), actual in SU/SEC",
        SRGMMAX: "Max memory limit",
        SRGMACT: "Memory used, actual",


        SUMGRP: "Group name",
        SUMTYP: "Type of WLM group",
        SUMIMP: "Importance of service class period",
        SUMGOA: "Goal type",
        SUMRES: "Name of resource group or tenant resource group",
        SUMRGTYP: "Definition of minimum and maximum capacity",
        SUMCRIT: "Indicator whether Storage Critical or CPU Critical, or both (S, C, or SC)",
        SUMHONP: "Ind. specialty engine eligible work in this SC will be prevented from being offloaded to CPs for help proc (N)",
        SUMEGRP: "Description of WLM group",
        SUMRGSPC: "Include specialty processor consumption",
        SUMRCTNT: "Rep.Cls is a tenant Rep.Cls",
        SUMVEG: "Execution velocity goal",
        SUMEVA: "Execution velocity actual",
        SUMRTGTM: "R.tme goal [msecs]",
        SUMRTGP: "R.tme goal percentile",
        SUMRTATM: "R.tme actual [msecs]",
        SUMRTAP: "R.tme actual percentile",
        SUMPFID: "Performance index",
        SUMTRAN: "Ended transactions / second",
        SUMARTWM: "Wait time [msecs]",
        SUMARTAM: "Execution time [msecs]",
        SUMARTTM: "Actual (total) R.tme [msecs]",
        SUMARTQM: "Queued time [msecs]",
        SUMARTRM: "R/S affinity time [msecs]",
        SUMARTIM: "Ineligible queue time [msecs]",
        SUMARTCM: "JCL conversion time [msecs]",
        SUMDUR: "Duration",
        SUMSMI: "Service rate (capacity), min.",
        SUMSMA: "Service rate (capacity), max.",
        SUMSRA: "Service rate (capacity), actual",
        SUMMLIM: "Maximum memory limit in GB",
        SUMRTGT: "R.tme goal [secs]",
        SUMRTAT: "R.tme actual [secs]",
        SUMARTW: "Wait time [secs]",
        SUMARTA: "Execution time [secs]",
        SUMARTT: "Actual (total) R.tme [secs]",
        SUMARTQ: "Queued time [secs]",
        SUMARTR: "R/S affinity time [secs]",
        SUMARTI: "Ineligible queue time [secs]",
        SUMARTC: "JCL conversion time [secs]",
        SUMMEMUS: "Memory used, actual",


        XCFPJOB: "Jobname",
        XCFPCLA: "Class (A, B, O, S, or T)",
        XCFPDMN: "Domain number; no longer used",
        XCFPPGN: "Performance group number; no longer used",
        XCFPSVCL: "Service class name",
        XCFPODEL: "Overall delay",
        XCF1SDEL: "Delay percentage (Path 1)",
        XCF1PATH: "Path 1",
        XCF2SDEL: "Delay percentage (Path 2)",
        XCF2PATH: "Path 2",
        XCF3SDEL: "Delay percentage (Path 3)",
        XCF3PATH: "Path 3",
        XCF4SDEL: "Delay percentage (Path 4)",
        XCF4PATH: "Path 4",


        ZFFPFILE: "FS detailed data",
        ZFFPFSN: "FS name",
        ZFFPSYSC: "Connected system",
        ZFFPSYSO: "Owning system",
        ZFFPMODE: "FS mode",
        ZFFPFSMP: "Mount point",
        ZFFPFSVN: "Vnodes",
        ZFFPFSVU: "USS held vnodes",
        ZFFPOBJT: "Tokens",
        ZFFPSIZE: "Maximum size",
        ZFFPUSGP: "Currently used space percentage",
        ZFFPAPIR: "I/O rate (read + write) by applications",
        ZFFPAPRT: "Response time (read + write) by applications",
        ZFFPAPRP: "Percentage of read operations in I/O rate",
        ZFFPAPXR: "XCF rate (read + write)",
        ZFFPOBJO: "Open objects",
        ZFFPFSUC: "User cache 4K pages",
        ZFFPFSMC: "Metadata cache 8K pages",
        ZFFPAPRR: "Application read rate",
        ZFFPARRT: "Application read response time",
        ZFFPXFRR: "XCF read rate",
        ZFFPXRRT: "XCF read response time",
        ZFFPIORR: "Aggregate read rate",
        ZFFPAPWR: "Application write rate",
        ZFFPAWRT: "Application write response time",
        ZFFPXFWR: "XCF write rate",
        ZFFPXWRT: "XCF write response time",
        ZFFPIOWR: "Aggregate write rate",
        ZFFPESPC: "ENOSPC errors",
        ZFFPEDIO: "Disk I/O errors",
        ZFFPEXCF: "XCF communication failures",
        ZFFPOPCA: "Cancelled operations",


        ZFKPSYS: "System name",
        ZFKPRQRL: "Request rate local",
        ZFKPRQRR: "Request rate remote",
        ZFKPXFRL: "XCF rate local",
        ZFKPXFRR: "XCF rate remote",
        ZFKPRPTL: "Response time local",
        ZFKPRPTR: "Response time remote",

        
        ZFOPSYS: "System name",
        ZFOPIORP: "Avg response time I/O %",
        ZFOPLORP: "Avg response time Lock %",
        ZFOPSLRP: "Avg response time Sleep %",
        ZFOPUCRT: "User cache request rate",
        ZFOPUCHP: "User cache hit %",
        ZFOPVCRT: "Vnode cache request rate",
        ZFOPVCHP: "Vnode cache hit %",
        ZFOPMCRT: "Metadata cache request rate",
        ZFOPMCHP: "Metadata cache hit %",
        ZFOPITYn: "IO summary: type I/O request (n:1,2,3)",
        ZFOPICTn: "IO summary: total number of I/O requests (n:1,2,3)",
        ZFOPIWTn: "IO summary: number of I/O requests waiting (n:1,2,3)",
        ZFOPICAn: "IO summary: number of I/O requests cancelled (n:1,2,3)",
        ZFOPIMGn: "IO summary: number of I/O requests merged (n:1,2,3)",
        ZFOPUCSZ: "User cache size",
        ZFOPUCSF: "User cache storage fixed",
        ZFOPUCTP: "User cache number of total pages",
        ZFOPUCFP: "User cache number of free pages",
        ZFOPUCSG: "User cache number of segments",
        ZFOPUCRR: "User cache read rate",
        ZFOPUCRH: "User cache read hit %",
        ZFOPUCRD: "User cache read delay %",
        ZFOPUCAR: "User cache asynchronous read rate",
        ZFOPUCWR: "User cache write rate",
        ZFOPUCWH: "User cache write hit %",
        ZFOPUCWD: "User cache write delay %",
        ZFOPUCSW: "User cache scheduled writes rate",
        ZFOPUCRP: "User cache read %",
        ZFOPUCDP: "User cache delay %",
        ZFOPUCRW: "User cache number of page reclaim writes",
        ZFOPUCFS: "User cache number of file synchronization requests",
        ZFOPVCSZ: "Vnode cache size",
        ZFOPVCAL: "Vnode cache number of currently allocated vnodes",
        ZFOPVCSN: "Vnode cache size of a vnode data structure",
        ZFOPVCEX: "Vnode cache number of extended vnodes",
        ZFOPVCSE: "Vnode cache size of an extended vnode",
        ZFOPVCOP: "Vnode cache number of open vnodes",
        ZFOPVCHE: "Vnode cache number of held vnodes",
        ZFOPVCRQ: "Vnode cache total number of requests",
        ZFOPVCCR: "Vnode cache number of requests to allocate (create) vnodes",
        ZFOPVCDL: "Vnode cache number of requests to delete vnodes",
        ZFOPMCSZ: "Metadata cache size",
        ZFOPMCSF: "Metadata cache storage fixed",
        ZFOPMCBU: "Metadata cache number of buffers",
        ZFOPMCRQ: "Metadata cache total number of requests",
        ZFOPMCUD: "Metadata cache number of updates",
        ZFOPMCPW: "Metadata cache number of partial writes"
        */
    }
}